package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Accountsheads generated by hbm2java
 */
public class Accountsheads  implements java.io.Serializable {


     private String acccode;
     private Ledgermaster ledgermaster;
     private Accountgroups accountgroups;
     private String accname;
     private Set voucherdetailses = new HashSet(0);
     private Set voucherdetailshistories = new HashSet(0);

    public Accountsheads() {
    }

	
    public Accountsheads(String acccode) {
        this.acccode = acccode;
    }
    public Accountsheads(String acccode, Ledgermaster ledgermaster, Accountgroups accountgroups, String accname, Set voucherdetailses, Set voucherdetailshistories) {
       this.acccode = acccode;
       this.ledgermaster = ledgermaster;
       this.accountgroups = accountgroups;
       this.accname = accname;
       this.voucherdetailses = voucherdetailses;
       this.voucherdetailshistories = voucherdetailshistories;
    }
   
    public String getAcccode() {
        return this.acccode;
    }
    
    public void setAcccode(String acccode) {
        this.acccode = acccode;
    }
    public Ledgermaster getLedgermaster() {
        return this.ledgermaster;
    }
    
    public void setLedgermaster(Ledgermaster ledgermaster) {
        this.ledgermaster = ledgermaster;
    }
    public Accountgroups getAccountgroups() {
        return this.accountgroups;
    }
    
    public void setAccountgroups(Accountgroups accountgroups) {
        this.accountgroups = accountgroups;
    }
    public String getAccname() {
        return this.accname;
    }
    
    public void setAccname(String accname) {
        this.accname = accname;
    }
    public Set getVoucherdetailses() {
        return this.voucherdetailses;
    }
    
    public void setVoucherdetailses(Set voucherdetailses) {
        this.voucherdetailses = voucherdetailses;
    }
    public Set getVoucherdetailshistories() {
        return this.voucherdetailshistories;
    }
    
    public void setVoucherdetailshistories(Set voucherdetailshistories) {
        this.voucherdetailshistories = voucherdetailshistories;
    }




}


