package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Accountingyear generated by hbm2java
 */
public class Accountingyear  implements java.io.Serializable {


     private String id;
     private Integer startmonth;
     private Integer startyear;
     private Integer endmonth;
     private Integer endyear;
     private Set brsdetailses = new HashSet(0);
     private Set accountingserialnos = new HashSet(0);
     private Set vouchers = new HashSet(0);
     private Set epfloanapplications = new HashSet(0);
     private Set voucherhistories = new HashSet(0);
     private Set epfopeningbalances = new HashSet(0);
     private Set bankreconciliationdetailses = new HashSet(0);

    public Accountingyear() {
    }

	
    public Accountingyear(String id) {
        this.id = id;
    }
    public Accountingyear(String id, Integer startmonth, Integer startyear, Integer endmonth, Integer endyear, Set brsdetailses, Set accountingserialnos, Set vouchers, Set epfloanapplications, Set voucherhistories, Set epfopeningbalances, Set bankreconciliationdetailses) {
       this.id = id;
       this.startmonth = startmonth;
       this.startyear = startyear;
       this.endmonth = endmonth;
       this.endyear = endyear;
       this.brsdetailses = brsdetailses;
       this.accountingserialnos = accountingserialnos;
       this.vouchers = vouchers;
       this.epfloanapplications = epfloanapplications;
       this.voucherhistories = voucherhistories;
       this.epfopeningbalances = epfopeningbalances;
       this.bankreconciliationdetailses = bankreconciliationdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getStartmonth() {
        return this.startmonth;
    }
    
    public void setStartmonth(Integer startmonth) {
        this.startmonth = startmonth;
    }
    public Integer getStartyear() {
        return this.startyear;
    }
    
    public void setStartyear(Integer startyear) {
        this.startyear = startyear;
    }
    public Integer getEndmonth() {
        return this.endmonth;
    }
    
    public void setEndmonth(Integer endmonth) {
        this.endmonth = endmonth;
    }
    public Integer getEndyear() {
        return this.endyear;
    }
    
    public void setEndyear(Integer endyear) {
        this.endyear = endyear;
    }
    public Set getBrsdetailses() {
        return this.brsdetailses;
    }
    
    public void setBrsdetailses(Set brsdetailses) {
        this.brsdetailses = brsdetailses;
    }
    public Set getAccountingserialnos() {
        return this.accountingserialnos;
    }
    
    public void setAccountingserialnos(Set accountingserialnos) {
        this.accountingserialnos = accountingserialnos;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }
    public Set getEpfloanapplications() {
        return this.epfloanapplications;
    }
    
    public void setEpfloanapplications(Set epfloanapplications) {
        this.epfloanapplications = epfloanapplications;
    }
    public Set getVoucherhistories() {
        return this.voucherhistories;
    }
    
    public void setVoucherhistories(Set voucherhistories) {
        this.voucherhistories = voucherhistories;
    }
    public Set getEpfopeningbalances() {
        return this.epfopeningbalances;
    }
    
    public void setEpfopeningbalances(Set epfopeningbalances) {
        this.epfopeningbalances = epfopeningbalances;
    }
    public Set getBankreconciliationdetailses() {
        return this.bankreconciliationdetailses;
    }
    
    public void setBankreconciliationdetailses(Set bankreconciliationdetailses) {
        this.bankreconciliationdetailses = bankreconciliationdetailses;
    }




}


