package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Accountsbooks generated by hbm2java
 */
public class Accountsbooks  implements java.io.Serializable {


     private String code;
     private String bookname;
     private String grouptype;
     private Set voucherhistories = new HashSet(0);
     private Set vouchers = new HashSet(0);
     private Set brsdetailses = new HashSet(0);

    public Accountsbooks() {
    }

	
    public Accountsbooks(String code) {
        this.code = code;
    }
    public Accountsbooks(String code, String bookname, String grouptype, Set voucherhistories, Set vouchers, Set brsdetailses) {
       this.code = code;
       this.bookname = bookname;
       this.grouptype = grouptype;
       this.voucherhistories = voucherhistories;
       this.vouchers = vouchers;
       this.brsdetailses = brsdetailses;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
    public String getGrouptype() {
        return this.grouptype;
    }
    
    public void setGrouptype(String grouptype) {
        this.grouptype = grouptype;
    }
    public Set getVoucherhistories() {
        return this.voucherhistories;
    }
    
    public void setVoucherhistories(Set voucherhistories) {
        this.voucherhistories = voucherhistories;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }
    public Set getBrsdetailses() {
        return this.brsdetailses;
    }
    
    public void setBrsdetailses(Set brsdetailses) {
        this.brsdetailses = brsdetailses;
    }




}


