package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Accountingserialno generated by hbm2java
 */
public class Accountingserialno  implements java.io.Serializable {


     private AccountingserialnoId id;
     private Accountingyear accountingyear;
     private String regionname;
     private Long employeeearningsslno;
     private Long employeeearningdetailsslno;
     private Long payrollprocessingdetailsid;
     private Long employeedeductionstransactionsid;
     private Long employeeearningstransactionsid;
     private Long employeedeductionsslno;
     private Long employeedeductiondetailsslno;
     private Long employeeattendanceid;
     private Long employeeloansandadvancesid;
     private Long employeeloansandadvancesdetailsid;
     private Long employeerecoveriesid;
     private Long employeerecoverydetailsid;
     private Long salarystructureactualid;
     private Long employeedeductiondetailsactualid;
     private Long employeeearningsdetailsactualid;
     private Long payrollprocessingid;
     private Long salarystructureid;
     private Long miscdeductionsid;
     private Long earningslapdetailsid;
     private Boolean synchronized_;
     private Long salarydeductionothersid;
     private Long supplementatypaybillid;
     private Long supplementarypayrollprocessingdetailsid;
     private Long supplementaryemployeeearningstransactionsid;
     private Long supplementaryemployeedeductionstransactionsid;
     private Long supplementarysalarystructureid;
     private Long supplementaryemployeeearningsdetailsid;
     private Long supplementaryemployeedeductiondetailsid;
     private Long supplementaryemployeeloansandadvancesdetailsid;
     private Long employeeprovidentfundothersid;
     private Long employeedeductionaccountcodeid;
     private Long incrementarrearreferenceid;
     private Long paymentvoucherid;
     private Long voucherdetails;
     private Long receiptpaymentdetailsid;
     private Long partyledgerid;
     private Long bankledgerid;
     private Long vatonpurchase;
     private Long vatonsales;
     private Long bankvoucherid;
     private Long receiptvoucherid;
     private Long journalvoucherid;
     private Long epfloanapplicationid;
     private Long bankchallanid;
     private Long ancillaryadjaccid;
     private Long voucherhistoryid;
     private Long voucherdetailshistoryid;
     private Long receiptpaymentdetailshistoryid;
     private Long taxoncst;
     private Long dabatchid;
     private String irscode;
     private Long interregionaccountsid;
     private Long interregionaccountsreconcil;
     private Long budgetdetailsid;
     private Long payrollvoucherid;
     private Long bankreconciliationdetailsid;
     private Long monthlyexpenditureid;
     private String billssigningauthority;
     private Long brsdetailsid;

    public Accountingserialno() {
    }

	
    public Accountingserialno(AccountingserialnoId id, Accountingyear accountingyear) {
        this.id = id;
        this.accountingyear = accountingyear;
    }
    public Accountingserialno(AccountingserialnoId id, Accountingyear accountingyear, String regionname, Long employeeearningsslno, Long employeeearningdetailsslno, Long payrollprocessingdetailsid, Long employeedeductionstransactionsid, Long employeeearningstransactionsid, Long employeedeductionsslno, Long employeedeductiondetailsslno, Long employeeattendanceid, Long employeeloansandadvancesid, Long employeeloansandadvancesdetailsid, Long employeerecoveriesid, Long employeerecoverydetailsid, Long salarystructureactualid, Long employeedeductiondetailsactualid, Long employeeearningsdetailsactualid, Long payrollprocessingid, Long salarystructureid, Long miscdeductionsid, Long earningslapdetailsid, Boolean synchronized_, Long salarydeductionothersid, Long supplementatypaybillid, Long supplementarypayrollprocessingdetailsid, Long supplementaryemployeeearningstransactionsid, Long supplementaryemployeedeductionstransactionsid, Long supplementarysalarystructureid, Long supplementaryemployeeearningsdetailsid, Long supplementaryemployeedeductiondetailsid, Long supplementaryemployeeloansandadvancesdetailsid, Long employeeprovidentfundothersid, Long employeedeductionaccountcodeid, Long incrementarrearreferenceid, Long paymentvoucherid, Long voucherdetails, Long receiptpaymentdetailsid, Long partyledgerid, Long bankledgerid, Long vatonpurchase, Long vatonsales, Long bankvoucherid, Long receiptvoucherid, Long journalvoucherid, Long epfloanapplicationid, Long bankchallanid, Long ancillaryadjaccid, Long voucherhistoryid, Long voucherdetailshistoryid, Long receiptpaymentdetailshistoryid, Long taxoncst, Long dabatchid, String irscode, Long interregionaccountsid, Long interregionaccountsreconcil, Long budgetdetailsid, Long payrollvoucherid, Long bankreconciliationdetailsid, Long monthlyexpenditureid, String billssigningauthority, Long brsdetailsid) {
       this.id = id;
       this.accountingyear = accountingyear;
       this.regionname = regionname;
       this.employeeearningsslno = employeeearningsslno;
       this.employeeearningdetailsslno = employeeearningdetailsslno;
       this.payrollprocessingdetailsid = payrollprocessingdetailsid;
       this.employeedeductionstransactionsid = employeedeductionstransactionsid;
       this.employeeearningstransactionsid = employeeearningstransactionsid;
       this.employeedeductionsslno = employeedeductionsslno;
       this.employeedeductiondetailsslno = employeedeductiondetailsslno;
       this.employeeattendanceid = employeeattendanceid;
       this.employeeloansandadvancesid = employeeloansandadvancesid;
       this.employeeloansandadvancesdetailsid = employeeloansandadvancesdetailsid;
       this.employeerecoveriesid = employeerecoveriesid;
       this.employeerecoverydetailsid = employeerecoverydetailsid;
       this.salarystructureactualid = salarystructureactualid;
       this.employeedeductiondetailsactualid = employeedeductiondetailsactualid;
       this.employeeearningsdetailsactualid = employeeearningsdetailsactualid;
       this.payrollprocessingid = payrollprocessingid;
       this.salarystructureid = salarystructureid;
       this.miscdeductionsid = miscdeductionsid;
       this.earningslapdetailsid = earningslapdetailsid;
       this.synchronized_ = synchronized_;
       this.salarydeductionothersid = salarydeductionothersid;
       this.supplementatypaybillid = supplementatypaybillid;
       this.supplementarypayrollprocessingdetailsid = supplementarypayrollprocessingdetailsid;
       this.supplementaryemployeeearningstransactionsid = supplementaryemployeeearningstransactionsid;
       this.supplementaryemployeedeductionstransactionsid = supplementaryemployeedeductionstransactionsid;
       this.supplementarysalarystructureid = supplementarysalarystructureid;
       this.supplementaryemployeeearningsdetailsid = supplementaryemployeeearningsdetailsid;
       this.supplementaryemployeedeductiondetailsid = supplementaryemployeedeductiondetailsid;
       this.supplementaryemployeeloansandadvancesdetailsid = supplementaryemployeeloansandadvancesdetailsid;
       this.employeeprovidentfundothersid = employeeprovidentfundothersid;
       this.employeedeductionaccountcodeid = employeedeductionaccountcodeid;
       this.incrementarrearreferenceid = incrementarrearreferenceid;
       this.paymentvoucherid = paymentvoucherid;
       this.voucherdetails = voucherdetails;
       this.receiptpaymentdetailsid = receiptpaymentdetailsid;
       this.partyledgerid = partyledgerid;
       this.bankledgerid = bankledgerid;
       this.vatonpurchase = vatonpurchase;
       this.vatonsales = vatonsales;
       this.bankvoucherid = bankvoucherid;
       this.receiptvoucherid = receiptvoucherid;
       this.journalvoucherid = journalvoucherid;
       this.epfloanapplicationid = epfloanapplicationid;
       this.bankchallanid = bankchallanid;
       this.ancillaryadjaccid = ancillaryadjaccid;
       this.voucherhistoryid = voucherhistoryid;
       this.voucherdetailshistoryid = voucherdetailshistoryid;
       this.receiptpaymentdetailshistoryid = receiptpaymentdetailshistoryid;
       this.taxoncst = taxoncst;
       this.dabatchid = dabatchid;
       this.irscode = irscode;
       this.interregionaccountsid = interregionaccountsid;
       this.interregionaccountsreconcil = interregionaccountsreconcil;
       this.budgetdetailsid = budgetdetailsid;
       this.payrollvoucherid = payrollvoucherid;
       this.bankreconciliationdetailsid = bankreconciliationdetailsid;
       this.monthlyexpenditureid = monthlyexpenditureid;
       this.billssigningauthority = billssigningauthority;
       this.brsdetailsid = brsdetailsid;
    }
   
    public AccountingserialnoId getId() {
        return this.id;
    }
    
    public void setId(AccountingserialnoId id) {
        this.id = id;
    }
    public Accountingyear getAccountingyear() {
        return this.accountingyear;
    }
    
    public void setAccountingyear(Accountingyear accountingyear) {
        this.accountingyear = accountingyear;
    }
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }
    public Long getEmployeeearningsslno() {
        return this.employeeearningsslno;
    }
    
    public void setEmployeeearningsslno(Long employeeearningsslno) {
        this.employeeearningsslno = employeeearningsslno;
    }
    public Long getEmployeeearningdetailsslno() {
        return this.employeeearningdetailsslno;
    }
    
    public void setEmployeeearningdetailsslno(Long employeeearningdetailsslno) {
        this.employeeearningdetailsslno = employeeearningdetailsslno;
    }
    public Long getPayrollprocessingdetailsid() {
        return this.payrollprocessingdetailsid;
    }
    
    public void setPayrollprocessingdetailsid(Long payrollprocessingdetailsid) {
        this.payrollprocessingdetailsid = payrollprocessingdetailsid;
    }
    public Long getEmployeedeductionstransactionsid() {
        return this.employeedeductionstransactionsid;
    }
    
    public void setEmployeedeductionstransactionsid(Long employeedeductionstransactionsid) {
        this.employeedeductionstransactionsid = employeedeductionstransactionsid;
    }
    public Long getEmployeeearningstransactionsid() {
        return this.employeeearningstransactionsid;
    }
    
    public void setEmployeeearningstransactionsid(Long employeeearningstransactionsid) {
        this.employeeearningstransactionsid = employeeearningstransactionsid;
    }
    public Long getEmployeedeductionsslno() {
        return this.employeedeductionsslno;
    }
    
    public void setEmployeedeductionsslno(Long employeedeductionsslno) {
        this.employeedeductionsslno = employeedeductionsslno;
    }
    public Long getEmployeedeductiondetailsslno() {
        return this.employeedeductiondetailsslno;
    }
    
    public void setEmployeedeductiondetailsslno(Long employeedeductiondetailsslno) {
        this.employeedeductiondetailsslno = employeedeductiondetailsslno;
    }
    public Long getEmployeeattendanceid() {
        return this.employeeattendanceid;
    }
    
    public void setEmployeeattendanceid(Long employeeattendanceid) {
        this.employeeattendanceid = employeeattendanceid;
    }
    public Long getEmployeeloansandadvancesid() {
        return this.employeeloansandadvancesid;
    }
    
    public void setEmployeeloansandadvancesid(Long employeeloansandadvancesid) {
        this.employeeloansandadvancesid = employeeloansandadvancesid;
    }
    public Long getEmployeeloansandadvancesdetailsid() {
        return this.employeeloansandadvancesdetailsid;
    }
    
    public void setEmployeeloansandadvancesdetailsid(Long employeeloansandadvancesdetailsid) {
        this.employeeloansandadvancesdetailsid = employeeloansandadvancesdetailsid;
    }
    public Long getEmployeerecoveriesid() {
        return this.employeerecoveriesid;
    }
    
    public void setEmployeerecoveriesid(Long employeerecoveriesid) {
        this.employeerecoveriesid = employeerecoveriesid;
    }
    public Long getEmployeerecoverydetailsid() {
        return this.employeerecoverydetailsid;
    }
    
    public void setEmployeerecoverydetailsid(Long employeerecoverydetailsid) {
        this.employeerecoverydetailsid = employeerecoverydetailsid;
    }
    public Long getSalarystructureactualid() {
        return this.salarystructureactualid;
    }
    
    public void setSalarystructureactualid(Long salarystructureactualid) {
        this.salarystructureactualid = salarystructureactualid;
    }
    public Long getEmployeedeductiondetailsactualid() {
        return this.employeedeductiondetailsactualid;
    }
    
    public void setEmployeedeductiondetailsactualid(Long employeedeductiondetailsactualid) {
        this.employeedeductiondetailsactualid = employeedeductiondetailsactualid;
    }
    public Long getEmployeeearningsdetailsactualid() {
        return this.employeeearningsdetailsactualid;
    }
    
    public void setEmployeeearningsdetailsactualid(Long employeeearningsdetailsactualid) {
        this.employeeearningsdetailsactualid = employeeearningsdetailsactualid;
    }
    public Long getPayrollprocessingid() {
        return this.payrollprocessingid;
    }
    
    public void setPayrollprocessingid(Long payrollprocessingid) {
        this.payrollprocessingid = payrollprocessingid;
    }
    public Long getSalarystructureid() {
        return this.salarystructureid;
    }
    
    public void setSalarystructureid(Long salarystructureid) {
        this.salarystructureid = salarystructureid;
    }
    public Long getMiscdeductionsid() {
        return this.miscdeductionsid;
    }
    
    public void setMiscdeductionsid(Long miscdeductionsid) {
        this.miscdeductionsid = miscdeductionsid;
    }
    public Long getEarningslapdetailsid() {
        return this.earningslapdetailsid;
    }
    
    public void setEarningslapdetailsid(Long earningslapdetailsid) {
        this.earningslapdetailsid = earningslapdetailsid;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public Long getSalarydeductionothersid() {
        return this.salarydeductionothersid;
    }
    
    public void setSalarydeductionothersid(Long salarydeductionothersid) {
        this.salarydeductionothersid = salarydeductionothersid;
    }
    public Long getSupplementatypaybillid() {
        return this.supplementatypaybillid;
    }
    
    public void setSupplementatypaybillid(Long supplementatypaybillid) {
        this.supplementatypaybillid = supplementatypaybillid;
    }
    public Long getSupplementarypayrollprocessingdetailsid() {
        return this.supplementarypayrollprocessingdetailsid;
    }
    
    public void setSupplementarypayrollprocessingdetailsid(Long supplementarypayrollprocessingdetailsid) {
        this.supplementarypayrollprocessingdetailsid = supplementarypayrollprocessingdetailsid;
    }
    public Long getSupplementaryemployeeearningstransactionsid() {
        return this.supplementaryemployeeearningstransactionsid;
    }
    
    public void setSupplementaryemployeeearningstransactionsid(Long supplementaryemployeeearningstransactionsid) {
        this.supplementaryemployeeearningstransactionsid = supplementaryemployeeearningstransactionsid;
    }
    public Long getSupplementaryemployeedeductionstransactionsid() {
        return this.supplementaryemployeedeductionstransactionsid;
    }
    
    public void setSupplementaryemployeedeductionstransactionsid(Long supplementaryemployeedeductionstransactionsid) {
        this.supplementaryemployeedeductionstransactionsid = supplementaryemployeedeductionstransactionsid;
    }
    public Long getSupplementarysalarystructureid() {
        return this.supplementarysalarystructureid;
    }
    
    public void setSupplementarysalarystructureid(Long supplementarysalarystructureid) {
        this.supplementarysalarystructureid = supplementarysalarystructureid;
    }
    public Long getSupplementaryemployeeearningsdetailsid() {
        return this.supplementaryemployeeearningsdetailsid;
    }
    
    public void setSupplementaryemployeeearningsdetailsid(Long supplementaryemployeeearningsdetailsid) {
        this.supplementaryemployeeearningsdetailsid = supplementaryemployeeearningsdetailsid;
    }
    public Long getSupplementaryemployeedeductiondetailsid() {
        return this.supplementaryemployeedeductiondetailsid;
    }
    
    public void setSupplementaryemployeedeductiondetailsid(Long supplementaryemployeedeductiondetailsid) {
        this.supplementaryemployeedeductiondetailsid = supplementaryemployeedeductiondetailsid;
    }
    public Long getSupplementaryemployeeloansandadvancesdetailsid() {
        return this.supplementaryemployeeloansandadvancesdetailsid;
    }
    
    public void setSupplementaryemployeeloansandadvancesdetailsid(Long supplementaryemployeeloansandadvancesdetailsid) {
        this.supplementaryemployeeloansandadvancesdetailsid = supplementaryemployeeloansandadvancesdetailsid;
    }
    public Long getEmployeeprovidentfundothersid() {
        return this.employeeprovidentfundothersid;
    }
    
    public void setEmployeeprovidentfundothersid(Long employeeprovidentfundothersid) {
        this.employeeprovidentfundothersid = employeeprovidentfundothersid;
    }
    public Long getEmployeedeductionaccountcodeid() {
        return this.employeedeductionaccountcodeid;
    }
    
    public void setEmployeedeductionaccountcodeid(Long employeedeductionaccountcodeid) {
        this.employeedeductionaccountcodeid = employeedeductionaccountcodeid;
    }
    public Long getIncrementarrearreferenceid() {
        return this.incrementarrearreferenceid;
    }
    
    public void setIncrementarrearreferenceid(Long incrementarrearreferenceid) {
        this.incrementarrearreferenceid = incrementarrearreferenceid;
    }
    public Long getPaymentvoucherid() {
        return this.paymentvoucherid;
    }
    
    public void setPaymentvoucherid(Long paymentvoucherid) {
        this.paymentvoucherid = paymentvoucherid;
    }
    public Long getVoucherdetails() {
        return this.voucherdetails;
    }
    
    public void setVoucherdetails(Long voucherdetails) {
        this.voucherdetails = voucherdetails;
    }
    public Long getReceiptpaymentdetailsid() {
        return this.receiptpaymentdetailsid;
    }
    
    public void setReceiptpaymentdetailsid(Long receiptpaymentdetailsid) {
        this.receiptpaymentdetailsid = receiptpaymentdetailsid;
    }
    public Long getPartyledgerid() {
        return this.partyledgerid;
    }
    
    public void setPartyledgerid(Long partyledgerid) {
        this.partyledgerid = partyledgerid;
    }
    public Long getBankledgerid() {
        return this.bankledgerid;
    }
    
    public void setBankledgerid(Long bankledgerid) {
        this.bankledgerid = bankledgerid;
    }
    public Long getVatonpurchase() {
        return this.vatonpurchase;
    }
    
    public void setVatonpurchase(Long vatonpurchase) {
        this.vatonpurchase = vatonpurchase;
    }
    public Long getVatonsales() {
        return this.vatonsales;
    }
    
    public void setVatonsales(Long vatonsales) {
        this.vatonsales = vatonsales;
    }
    public Long getBankvoucherid() {
        return this.bankvoucherid;
    }
    
    public void setBankvoucherid(Long bankvoucherid) {
        this.bankvoucherid = bankvoucherid;
    }
    public Long getReceiptvoucherid() {
        return this.receiptvoucherid;
    }
    
    public void setReceiptvoucherid(Long receiptvoucherid) {
        this.receiptvoucherid = receiptvoucherid;
    }
    public Long getJournalvoucherid() {
        return this.journalvoucherid;
    }
    
    public void setJournalvoucherid(Long journalvoucherid) {
        this.journalvoucherid = journalvoucherid;
    }
    public Long getEpfloanapplicationid() {
        return this.epfloanapplicationid;
    }
    
    public void setEpfloanapplicationid(Long epfloanapplicationid) {
        this.epfloanapplicationid = epfloanapplicationid;
    }
    public Long getBankchallanid() {
        return this.bankchallanid;
    }
    
    public void setBankchallanid(Long bankchallanid) {
        this.bankchallanid = bankchallanid;
    }
    public Long getAncillaryadjaccid() {
        return this.ancillaryadjaccid;
    }
    
    public void setAncillaryadjaccid(Long ancillaryadjaccid) {
        this.ancillaryadjaccid = ancillaryadjaccid;
    }
    public Long getVoucherhistoryid() {
        return this.voucherhistoryid;
    }
    
    public void setVoucherhistoryid(Long voucherhistoryid) {
        this.voucherhistoryid = voucherhistoryid;
    }
    public Long getVoucherdetailshistoryid() {
        return this.voucherdetailshistoryid;
    }
    
    public void setVoucherdetailshistoryid(Long voucherdetailshistoryid) {
        this.voucherdetailshistoryid = voucherdetailshistoryid;
    }
    public Long getReceiptpaymentdetailshistoryid() {
        return this.receiptpaymentdetailshistoryid;
    }
    
    public void setReceiptpaymentdetailshistoryid(Long receiptpaymentdetailshistoryid) {
        this.receiptpaymentdetailshistoryid = receiptpaymentdetailshistoryid;
    }
    public Long getTaxoncst() {
        return this.taxoncst;
    }
    
    public void setTaxoncst(Long taxoncst) {
        this.taxoncst = taxoncst;
    }
    public Long getDabatchid() {
        return this.dabatchid;
    }
    
    public void setDabatchid(Long dabatchid) {
        this.dabatchid = dabatchid;
    }
    public String getIrscode() {
        return this.irscode;
    }
    
    public void setIrscode(String irscode) {
        this.irscode = irscode;
    }
    public Long getInterregionaccountsid() {
        return this.interregionaccountsid;
    }
    
    public void setInterregionaccountsid(Long interregionaccountsid) {
        this.interregionaccountsid = interregionaccountsid;
    }
    public Long getInterregionaccountsreconcil() {
        return this.interregionaccountsreconcil;
    }
    
    public void setInterregionaccountsreconcil(Long interregionaccountsreconcil) {
        this.interregionaccountsreconcil = interregionaccountsreconcil;
    }
    public Long getBudgetdetailsid() {
        return this.budgetdetailsid;
    }
    
    public void setBudgetdetailsid(Long budgetdetailsid) {
        this.budgetdetailsid = budgetdetailsid;
    }
    public Long getPayrollvoucherid() {
        return this.payrollvoucherid;
    }
    
    public void setPayrollvoucherid(Long payrollvoucherid) {
        this.payrollvoucherid = payrollvoucherid;
    }
    public Long getBankreconciliationdetailsid() {
        return this.bankreconciliationdetailsid;
    }
    
    public void setBankreconciliationdetailsid(Long bankreconciliationdetailsid) {
        this.bankreconciliationdetailsid = bankreconciliationdetailsid;
    }
    public Long getMonthlyexpenditureid() {
        return this.monthlyexpenditureid;
    }
    
    public void setMonthlyexpenditureid(Long monthlyexpenditureid) {
        this.monthlyexpenditureid = monthlyexpenditureid;
    }
    public String getBillssigningauthority() {
        return this.billssigningauthority;
    }
    
    public void setBillssigningauthority(String billssigningauthority) {
        this.billssigningauthority = billssigningauthority;
    }
    public Long getBrsdetailsid() {
        return this.brsdetailsid;
    }
    
    public void setBrsdetailsid(Long brsdetailsid) {
        this.brsdetailsid = brsdetailsid;
    }




}


