package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ancillaryaccountadjcode generated by hbm2java
 */
public class Ancillaryaccountadjcode  implements java.io.Serializable {


     private String id;
     private String name;
     private String group;
     private BigDecimal tax;
     private Set ancillaruadjdetailses = new HashSet(0);

    public Ancillaryaccountadjcode() {
    }

	
    public Ancillaryaccountadjcode(String id) {
        this.id = id;
    }
    public Ancillaryaccountadjcode(String id, String name, String group, BigDecimal tax, Set ancillaruadjdetailses) {
       this.id = id;
       this.name = name;
       this.group = group;
       this.tax = tax;
       this.ancillaruadjdetailses = ancillaruadjdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGroup() {
        return this.group;
    }
    
    public void setGroup(String group) {
        this.group = group;
    }
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }
    public Set getAncillaruadjdetailses() {
        return this.ancillaruadjdetailses;
    }
    
    public void setAncillaruadjdetailses(Set ancillaruadjdetailses) {
        this.ancillaruadjdetailses = ancillaruadjdetailses;
    }




}


