package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Bankledger generated by hbm2java
 */
public class Bankledger  implements java.io.Serializable {


     private String code;
     private Regionmaster regionmaster;
     private String bankname;
     private String branchname;
     private String accountno;
     private String add1;
     private String add2;
     private String add3;
     private String zipcode;
     private Set receiptpaymentdetailshistories = new HashSet(0);
     private Set chequedetailses = new HashSet(0);
     private Set bankreconciliationdetailses = new HashSet(0);
     private Set bankchallans = new HashSet(0);
     private Set receiptpaymentdetailses = new HashSet(0);

    public Bankledger() {
    }

	
    public Bankledger(String code) {
        this.code = code;
    }
    public Bankledger(String code, Regionmaster regionmaster, String bankname, String branchname, String accountno, String add1, String add2, String add3, String zipcode, Set receiptpaymentdetailshistories, Set chequedetailses, Set bankreconciliationdetailses, Set bankchallans, Set receiptpaymentdetailses) {
       this.code = code;
       this.regionmaster = regionmaster;
       this.bankname = bankname;
       this.branchname = branchname;
       this.accountno = accountno;
       this.add1 = add1;
       this.add2 = add2;
       this.add3 = add3;
       this.zipcode = zipcode;
       this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
       this.chequedetailses = chequedetailses;
       this.bankreconciliationdetailses = bankreconciliationdetailses;
       this.bankchallans = bankchallans;
       this.receiptpaymentdetailses = receiptpaymentdetailses;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public String getBankname() {
        return this.bankname;
    }
    
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
    public String getBranchname() {
        return this.branchname;
    }
    
    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }
    public String getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }
    public String getAdd1() {
        return this.add1;
    }
    
    public void setAdd1(String add1) {
        this.add1 = add1;
    }
    public String getAdd2() {
        return this.add2;
    }
    
    public void setAdd2(String add2) {
        this.add2 = add2;
    }
    public String getAdd3() {
        return this.add3;
    }
    
    public void setAdd3(String add3) {
        this.add3 = add3;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public Set getReceiptpaymentdetailshistories() {
        return this.receiptpaymentdetailshistories;
    }
    
    public void setReceiptpaymentdetailshistories(Set receiptpaymentdetailshistories) {
        this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }
    public Set getChequedetailses() {
        return this.chequedetailses;
    }
    
    public void setChequedetailses(Set chequedetailses) {
        this.chequedetailses = chequedetailses;
    }
    public Set getBankreconciliationdetailses() {
        return this.bankreconciliationdetailses;
    }
    
    public void setBankreconciliationdetailses(Set bankreconciliationdetailses) {
        this.bankreconciliationdetailses = bankreconciliationdetailses;
    }
    public Set getBankchallans() {
        return this.bankchallans;
    }
    
    public void setBankchallans(Set bankchallans) {
        this.bankchallans = bankchallans;
    }
    public Set getReceiptpaymentdetailses() {
        return this.receiptpaymentdetailses;
    }
    
    public void setReceiptpaymentdetailses(Set receiptpaymentdetailses) {
        this.receiptpaymentdetailses = receiptpaymentdetailses;
    }




}


