package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bankchallan generated by hbm2java
 */
public class Bankchallan  implements java.io.Serializable {


     private String id;
     private Bankledger bankledger;
     private Regionmaster regionmaster;
     private Date challandate;
     private String remarks;
     private Boolean cancelled;
     private BigDecimal amount;
     private String type;
     private Date printdate;
     private Set receiptpaymentdetailses = new HashSet(0);
     private Set receiptpaymentdetailshistories = new HashSet(0);

    public Bankchallan() {
    }

	
    public Bankchallan(String id) {
        this.id = id;
    }
    public Bankchallan(String id, Bankledger bankledger, Regionmaster regionmaster, Date challandate, String remarks, Boolean cancelled, BigDecimal amount, String type, Date printdate, Set receiptpaymentdetailses, Set receiptpaymentdetailshistories) {
       this.id = id;
       this.bankledger = bankledger;
       this.regionmaster = regionmaster;
       this.challandate = challandate;
       this.remarks = remarks;
       this.cancelled = cancelled;
       this.amount = amount;
       this.type = type;
       this.printdate = printdate;
       this.receiptpaymentdetailses = receiptpaymentdetailses;
       this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Bankledger getBankledger() {
        return this.bankledger;
    }
    
    public void setBankledger(Bankledger bankledger) {
        this.bankledger = bankledger;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public Date getChallandate() {
        return this.challandate;
    }
    
    public void setChallandate(Date challandate) {
        this.challandate = challandate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getPrintdate() {
        return this.printdate;
    }
    
    public void setPrintdate(Date printdate) {
        this.printdate = printdate;
    }
    public Set getReceiptpaymentdetailses() {
        return this.receiptpaymentdetailses;
    }
    
    public void setReceiptpaymentdetailses(Set receiptpaymentdetailses) {
        this.receiptpaymentdetailses = receiptpaymentdetailses;
    }
    public Set getReceiptpaymentdetailshistories() {
        return this.receiptpaymentdetailshistories;
    }
    
    public void setReceiptpaymentdetailshistories(Set receiptpaymentdetailshistories) {
        this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }




}


