package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Bonusdetails generated by hbm2java
 */
public class Bonusdetails  implements java.io.Serializable {


     private int id;
     private Regionmaster regionmaster;
     private String epfno;
     private Integer year;
     private Integer month;
     private BigDecimal earningsamount;
     private BigDecimal deductionamount;
     private String bonustype;

    public Bonusdetails() {
    }

	
    public Bonusdetails(int id) {
        this.id = id;
    }
    public Bonusdetails(int id, Regionmaster regionmaster, String epfno, Integer year, Integer month, BigDecimal earningsamount, BigDecimal deductionamount, String bonustype) {
       this.id = id;
       this.regionmaster = regionmaster;
       this.epfno = epfno;
       this.year = year;
       this.month = month;
       this.earningsamount = earningsamount;
       this.deductionamount = deductionamount;
       this.bonustype = bonustype;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public String getEpfno() {
        return this.epfno;
    }
    
    public void setEpfno(String epfno) {
        this.epfno = epfno;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public BigDecimal getEarningsamount() {
        return this.earningsamount;
    }
    
    public void setEarningsamount(BigDecimal earningsamount) {
        this.earningsamount = earningsamount;
    }
    public BigDecimal getDeductionamount() {
        return this.deductionamount;
    }
    
    public void setDeductionamount(BigDecimal deductionamount) {
        this.deductionamount = deductionamount;
    }
    public String getBonustype() {
        return this.bonustype;
    }
    
    public void setBonustype(String bonustype) {
        this.bonustype = bonustype;
    }




}


