package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Brsledger generated by hbm2java
 */
public class Brsledger  implements java.io.Serializable {


     private int id;
     private String region;
     private String branchname;
     private String branchcode;

    public Brsledger() {
    }

	
    public Brsledger(int id) {
        this.id = id;
    }
    public Brsledger(int id, String region, String branchname, String branchcode) {
       this.id = id;
       this.region = region;
       this.branchname = branchname;
       this.branchcode = branchcode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getBranchname() {
        return this.branchname;
    }
    
    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }




}


