package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Budgetdetails generated by hbm2java
 */
public class Budgetdetails  implements java.io.Serializable {


     private String id;
     private Ledgermaster ledgermaster;
     private Budget budget;
     private Regionmaster regionmaster;
     private BigDecimal budgetestimate;
     private BigDecimal revisedbudgetestimate;
     private BigDecimal actualoffirsthalfyesr;
     private BigDecimal actualofsecondhalfyesr;
     private BigDecimal actual;
     private BigDecimal probableforsecondhalfyear;
     private BigDecimal hobudget;
     private BigDecimal horevisedbudget;
     private BigDecimal fma;
     private BigDecimal hofma;

    public Budgetdetails() {
    }

	
    public Budgetdetails(String id) {
        this.id = id;
    }
    public Budgetdetails(String id, Ledgermaster ledgermaster, Budget budget, Regionmaster regionmaster, BigDecimal budgetestimate, BigDecimal revisedbudgetestimate, BigDecimal actualoffirsthalfyesr, BigDecimal actualofsecondhalfyesr, BigDecimal actual, BigDecimal probableforsecondhalfyear, BigDecimal hobudget, BigDecimal horevisedbudget, BigDecimal fma, BigDecimal hofma) {
       this.id = id;
       this.ledgermaster = ledgermaster;
       this.budget = budget;
       this.regionmaster = regionmaster;
       this.budgetestimate = budgetestimate;
       this.revisedbudgetestimate = revisedbudgetestimate;
       this.actualoffirsthalfyesr = actualoffirsthalfyesr;
       this.actualofsecondhalfyesr = actualofsecondhalfyesr;
       this.actual = actual;
       this.probableforsecondhalfyear = probableforsecondhalfyear;
       this.hobudget = hobudget;
       this.horevisedbudget = horevisedbudget;
       this.fma = fma;
       this.hofma = hofma;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Ledgermaster getLedgermaster() {
        return this.ledgermaster;
    }
    
    public void setLedgermaster(Ledgermaster ledgermaster) {
        this.ledgermaster = ledgermaster;
    }
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public BigDecimal getBudgetestimate() {
        return this.budgetestimate;
    }
    
    public void setBudgetestimate(BigDecimal budgetestimate) {
        this.budgetestimate = budgetestimate;
    }
    public BigDecimal getRevisedbudgetestimate() {
        return this.revisedbudgetestimate;
    }
    
    public void setRevisedbudgetestimate(BigDecimal revisedbudgetestimate) {
        this.revisedbudgetestimate = revisedbudgetestimate;
    }
    public BigDecimal getActualoffirsthalfyesr() {
        return this.actualoffirsthalfyesr;
    }
    
    public void setActualoffirsthalfyesr(BigDecimal actualoffirsthalfyesr) {
        this.actualoffirsthalfyesr = actualoffirsthalfyesr;
    }
    public BigDecimal getActualofsecondhalfyesr() {
        return this.actualofsecondhalfyesr;
    }
    
    public void setActualofsecondhalfyesr(BigDecimal actualofsecondhalfyesr) {
        this.actualofsecondhalfyesr = actualofsecondhalfyesr;
    }
    public BigDecimal getActual() {
        return this.actual;
    }
    
    public void setActual(BigDecimal actual) {
        this.actual = actual;
    }
    public BigDecimal getProbableforsecondhalfyear() {
        return this.probableforsecondhalfyear;
    }
    
    public void setProbableforsecondhalfyear(BigDecimal probableforsecondhalfyear) {
        this.probableforsecondhalfyear = probableforsecondhalfyear;
    }
    public BigDecimal getHobudget() {
        return this.hobudget;
    }
    
    public void setHobudget(BigDecimal hobudget) {
        this.hobudget = hobudget;
    }
    public BigDecimal getHorevisedbudget() {
        return this.horevisedbudget;
    }
    
    public void setHorevisedbudget(BigDecimal horevisedbudget) {
        this.horevisedbudget = horevisedbudget;
    }
    public BigDecimal getFma() {
        return this.fma;
    }
    
    public void setFma(BigDecimal fma) {
        this.fma = fma;
    }
    public BigDecimal getHofma() {
        return this.hofma;
    }
    
    public void setHofma(BigDecimal hofma) {
        this.hofma = hofma;
    }




}


