package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Budget generated by hbm2java
 */
public class Budget  implements java.io.Serializable {


     private String id;
     private Integer startmonth;
     private Integer startyear;
     private Integer endmonth;
     private Integer endyear;
     private Set budgetdetailses = new HashSet(0);
     private Set monthlyexpendituredetailses = new HashSet(0);

    public Budget() {
    }

	
    public Budget(String id) {
        this.id = id;
    }
    public Budget(String id, Integer startmonth, Integer startyear, Integer endmonth, Integer endyear, Set budgetdetailses, Set monthlyexpendituredetailses) {
       this.id = id;
       this.startmonth = startmonth;
       this.startyear = startyear;
       this.endmonth = endmonth;
       this.endyear = endyear;
       this.budgetdetailses = budgetdetailses;
       this.monthlyexpendituredetailses = monthlyexpendituredetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getStartmonth() {
        return this.startmonth;
    }
    
    public void setStartmonth(Integer startmonth) {
        this.startmonth = startmonth;
    }
    public Integer getStartyear() {
        return this.startyear;
    }
    
    public void setStartyear(Integer startyear) {
        this.startyear = startyear;
    }
    public Integer getEndmonth() {
        return this.endmonth;
    }
    
    public void setEndmonth(Integer endmonth) {
        this.endmonth = endmonth;
    }
    public Integer getEndyear() {
        return this.endyear;
    }
    
    public void setEndyear(Integer endyear) {
        this.endyear = endyear;
    }
    public Set getBudgetdetailses() {
        return this.budgetdetailses;
    }
    
    public void setBudgetdetailses(Set budgetdetailses) {
        this.budgetdetailses = budgetdetailses;
    }
    public Set getMonthlyexpendituredetailses() {
        return this.monthlyexpendituredetailses;
    }
    
    public void setMonthlyexpendituredetailses(Set monthlyexpendituredetailses) {
        this.monthlyexpendituredetailses = monthlyexpendituredetailses;
    }




}


