package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Ccahra generated by hbm2java
 */
public class Ccahra  implements java.io.Serializable {


     private String ccahraid;
     private Paycodemaster paycodemaster;
     private String ccahra;
     private Boolean synchronized_;

    public Ccahra() {
    }

	
    public Ccahra(String ccahraid) {
        this.ccahraid = ccahraid;
    }
    public Ccahra(String ccahraid, Paycodemaster paycodemaster, String ccahra, Boolean synchronized_) {
       this.ccahraid = ccahraid;
       this.paycodemaster = paycodemaster;
       this.ccahra = ccahra;
       this.synchronized_ = synchronized_;
    }
   
    public String getCcahraid() {
        return this.ccahraid;
    }
    
    public void setCcahraid(String ccahraid) {
        this.ccahraid = ccahraid;
    }
    public Paycodemaster getPaycodemaster() {
        return this.paycodemaster;
    }
    
    public void setPaycodemaster(Paycodemaster paycodemaster) {
        this.paycodemaster = paycodemaster;
    }
    public String getCcahra() {
        return this.ccahra;
    }
    
    public void setCcahra(String ccahra) {
        this.ccahra = ccahra;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }




}


