package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Chequedetails generated by hbm2java
 */
public class Chequedetails  implements java.io.Serializable {


     private String id;
     private Bankledger bankledger;
     private String chequeno;
     private Set receiptpaymentdetailses = new HashSet(0);
     private Set receiptpaymentdetailshistories = new HashSet(0);

    public Chequedetails() {
    }

	
    public Chequedetails(String id) {
        this.id = id;
    }
    public Chequedetails(String id, Bankledger bankledger, String chequeno, Set receiptpaymentdetailses, Set receiptpaymentdetailshistories) {
       this.id = id;
       this.bankledger = bankledger;
       this.chequeno = chequeno;
       this.receiptpaymentdetailses = receiptpaymentdetailses;
       this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Bankledger getBankledger() {
        return this.bankledger;
    }
    
    public void setBankledger(Bankledger bankledger) {
        this.bankledger = bankledger;
    }
    public String getChequeno() {
        return this.chequeno;
    }
    
    public void setChequeno(String chequeno) {
        this.chequeno = chequeno;
    }
    public Set getReceiptpaymentdetailses() {
        return this.receiptpaymentdetailses;
    }
    
    public void setReceiptpaymentdetailses(Set receiptpaymentdetailses) {
        this.receiptpaymentdetailses = receiptpaymentdetailses;
    }
    public Set getReceiptpaymentdetailshistories() {
        return this.receiptpaymentdetailshistories;
    }
    
    public void setReceiptpaymentdetailshistories(Set receiptpaymentdetailshistories) {
        this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }




}


