package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Commoditymaster generated by hbm2java
 */
public class Commoditymaster  implements java.io.Serializable {


     private String id;
     private String name;
     private BigDecimal vatpercentage;
     private String code;
     private Integer commodityorder;
     private String commoditytype;
     private Boolean vatsales;
     private Boolean vatpurchase;
     private Boolean ismodimyonpurchase;
     private BigDecimal rate;
     private Set vatonpurchases = new HashSet(0);
     private Set vatonsaleses = new HashSet(0);

    public Commoditymaster() {
    }

	
    public Commoditymaster(String id) {
        this.id = id;
    }
    public Commoditymaster(String id, String name, BigDecimal vatpercentage, String code, Integer commodityorder, String commoditytype, Boolean vatsales, Boolean vatpurchase, Boolean ismodimyonpurchase, BigDecimal rate, Set vatonpurchases, Set vatonsaleses) {
       this.id = id;
       this.name = name;
       this.vatpercentage = vatpercentage;
       this.code = code;
       this.commodityorder = commodityorder;
       this.commoditytype = commoditytype;
       this.vatsales = vatsales;
       this.vatpurchase = vatpurchase;
       this.ismodimyonpurchase = ismodimyonpurchase;
       this.rate = rate;
       this.vatonpurchases = vatonpurchases;
       this.vatonsaleses = vatonsaleses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getVatpercentage() {
        return this.vatpercentage;
    }
    
    public void setVatpercentage(BigDecimal vatpercentage) {
        this.vatpercentage = vatpercentage;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getCommodityorder() {
        return this.commodityorder;
    }
    
    public void setCommodityorder(Integer commodityorder) {
        this.commodityorder = commodityorder;
    }
    public String getCommoditytype() {
        return this.commoditytype;
    }
    
    public void setCommoditytype(String commoditytype) {
        this.commoditytype = commoditytype;
    }
    public Boolean getVatsales() {
        return this.vatsales;
    }
    
    public void setVatsales(Boolean vatsales) {
        this.vatsales = vatsales;
    }
    public Boolean getVatpurchase() {
        return this.vatpurchase;
    }
    
    public void setVatpurchase(Boolean vatpurchase) {
        this.vatpurchase = vatpurchase;
    }
    public Boolean getIsmodimyonpurchase() {
        return this.ismodimyonpurchase;
    }
    
    public void setIsmodimyonpurchase(Boolean ismodimyonpurchase) {
        this.ismodimyonpurchase = ismodimyonpurchase;
    }
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }
    public Set getVatonpurchases() {
        return this.vatonpurchases;
    }
    
    public void setVatonpurchases(Set vatonpurchases) {
        this.vatonpurchases = vatonpurchases;
    }
    public Set getVatonsaleses() {
        return this.vatonsaleses;
    }
    
    public void setVatonsaleses(Set vatonsaleses) {
        this.vatonsaleses = vatonsaleses;
    }




}


