package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Daarreardiffentry generated by hbm2java
 */
public class Daarreardiffentry  implements java.io.Serializable {


     private String id;
     private String supplementarypayroll;
     private BigDecimal basic;
     private BigDecimal perpay;
     private BigDecimal gradepay;
     private BigDecimal due;
     private BigDecimal drawn;
     private String type;
     private BigDecimal arrear;
     private BigDecimal epf;
     private Integer month;
     private Integer year;

    public Daarreardiffentry() {
    }

	
    public Daarreardiffentry(String id) {
        this.id = id;
    }
    public Daarreardiffentry(String id, String supplementarypayroll, BigDecimal basic, BigDecimal perpay, BigDecimal gradepay, BigDecimal due, BigDecimal drawn, String type, BigDecimal arrear, BigDecimal epf, Integer month, Integer year) {
       this.id = id;
       this.supplementarypayroll = supplementarypayroll;
       this.basic = basic;
       this.perpay = perpay;
       this.gradepay = gradepay;
       this.due = due;
       this.drawn = drawn;
       this.type = type;
       this.arrear = arrear;
       this.epf = epf;
       this.month = month;
       this.year = year;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSupplementarypayroll() {
        return this.supplementarypayroll;
    }
    
    public void setSupplementarypayroll(String supplementarypayroll) {
        this.supplementarypayroll = supplementarypayroll;
    }
    public BigDecimal getBasic() {
        return this.basic;
    }
    
    public void setBasic(BigDecimal basic) {
        this.basic = basic;
    }
    public BigDecimal getPerpay() {
        return this.perpay;
    }
    
    public void setPerpay(BigDecimal perpay) {
        this.perpay = perpay;
    }
    public BigDecimal getGradepay() {
        return this.gradepay;
    }
    
    public void setGradepay(BigDecimal gradepay) {
        this.gradepay = gradepay;
    }
    public BigDecimal getDue() {
        return this.due;
    }
    
    public void setDue(BigDecimal due) {
        this.due = due;
    }
    public BigDecimal getDrawn() {
        return this.drawn;
    }
    
    public void setDrawn(BigDecimal drawn) {
        this.drawn = drawn;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getArrear() {
        return this.arrear;
    }
    
    public void setArrear(BigDecimal arrear) {
        this.arrear = arrear;
    }
    public BigDecimal getEpf() {
        return this.epf;
    }
    
    public void setEpf(BigDecimal epf) {
        this.epf = epf;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }




}


