package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Daarrear generated by hbm2java
 */
public class Daarrear  implements java.io.Serializable {


     private String id;
     private Regionmaster regionmaster;
     private String name;
     private String fileno;
     private Boolean cancelled;
     private Boolean active;
     private Set dabatchdetailses = new HashSet(0);

    public Daarrear() {
    }

	
    public Daarrear(String id) {
        this.id = id;
    }
    public Daarrear(String id, Regionmaster regionmaster, String name, String fileno, Boolean cancelled, Boolean active, Set dabatchdetailses) {
       this.id = id;
       this.regionmaster = regionmaster;
       this.name = name;
       this.fileno = fileno;
       this.cancelled = cancelled;
       this.active = active;
       this.dabatchdetailses = dabatchdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFileno() {
        return this.fileno;
    }
    
    public void setFileno(String fileno) {
        this.fileno = fileno;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getDabatchdetailses() {
        return this.dabatchdetailses;
    }
    
    public void setDabatchdetailses(Set dabatchdetailses) {
        this.dabatchdetailses = dabatchdetailses;
    }




}


