package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Designationmaster generated by hbm2java
 */
public class Designationmaster  implements java.io.Serializable {


     private String designationcode;
     private String designation;
     private String payscalecode;
     private String remarks;
     private String orderno;
     private Boolean synchronized_;
     private String designationgroup;

    public Designationmaster() {
    }

	
    public Designationmaster(String designationcode) {
        this.designationcode = designationcode;
    }
    public Designationmaster(String designationcode, String designation, String payscalecode, String remarks, String orderno, Boolean synchronized_, String designationgroup) {
       this.designationcode = designationcode;
       this.designation = designation;
       this.payscalecode = payscalecode;
       this.remarks = remarks;
       this.orderno = orderno;
       this.synchronized_ = synchronized_;
       this.designationgroup = designationgroup;
    }
   
    public String getDesignationcode() {
        return this.designationcode;
    }
    
    public void setDesignationcode(String designationcode) {
        this.designationcode = designationcode;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getPayscalecode() {
        return this.payscalecode;
    }
    
    public void setPayscalecode(String payscalecode) {
        this.payscalecode = payscalecode;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getDesignationgroup() {
        return this.designationgroup;
    }
    
    public void setDesignationgroup(String designationgroup) {
        this.designationgroup = designationgroup;
    }




}


