package com.onward.persistence.payroll;
// Generated 8 Jun, 2015 10:40:08 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Employeedetails generated by hbm2java
 */
public class Employeedetails  implements java.io.Serializable {


     private EmployeedetailsId id;
     private String detailtype1;
     private String detailtype2;
     private String detailtype3;
     private String createdby;
     private Date createddate;

    public Employeedetails() {
    }

	
    public Employeedetails(EmployeedetailsId id) {
        this.id = id;
    }
    public Employeedetails(EmployeedetailsId id, String detailtype1, String detailtype2, String detailtype3, String createdby, Date createddate) {
       this.id = id;
       this.detailtype1 = detailtype1;
       this.detailtype2 = detailtype2;
       this.detailtype3 = detailtype3;
       this.createdby = createdby;
       this.createddate = createddate;
    }
   
    public EmployeedetailsId getId() {
        return this.id;
    }
    
    public void setId(EmployeedetailsId id) {
        this.id = id;
    }
    public String getDetailtype1() {
        return this.detailtype1;
    }
    
    public void setDetailtype1(String detailtype1) {
        this.detailtype1 = detailtype1;
    }
    public String getDetailtype2() {
        return this.detailtype2;
    }
    
    public void setDetailtype2(String detailtype2) {
        this.detailtype2 = detailtype2;
    }
    public String getDetailtype3() {
        return this.detailtype3;
    }
    
    public void setDetailtype3(String detailtype3) {
        this.detailtype3 = detailtype3;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


