package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Employeerecoverydetails generated by hbm2java
 */
public class Employeerecoverydetails  implements java.io.Serializable {


     private String id;
     private Payrollprocessingdetails payrollprocessingdetails;
     private Employeerecoveries employeerecoveries;
     private Integer nthinstallment;
     private BigDecimal installmentamount;
     private BigDecimal loanbalance;
     private Boolean cancelled;
     private String accregion;
     private Date createddate;
     private String createdby;

    public Employeerecoverydetails() {
    }

	
    public Employeerecoverydetails(String id) {
        this.id = id;
    }
    public Employeerecoverydetails(String id, Payrollprocessingdetails payrollprocessingdetails, Employeerecoveries employeerecoveries, Integer nthinstallment, BigDecimal installmentamount, BigDecimal loanbalance, Boolean cancelled, String accregion, Date createddate, String createdby) {
       this.id = id;
       this.payrollprocessingdetails = payrollprocessingdetails;
       this.employeerecoveries = employeerecoveries;
       this.nthinstallment = nthinstallment;
       this.installmentamount = installmentamount;
       this.loanbalance = loanbalance;
       this.cancelled = cancelled;
       this.accregion = accregion;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Payrollprocessingdetails getPayrollprocessingdetails() {
        return this.payrollprocessingdetails;
    }
    
    public void setPayrollprocessingdetails(Payrollprocessingdetails payrollprocessingdetails) {
        this.payrollprocessingdetails = payrollprocessingdetails;
    }
    public Employeerecoveries getEmployeerecoveries() {
        return this.employeerecoveries;
    }
    
    public void setEmployeerecoveries(Employeerecoveries employeerecoveries) {
        this.employeerecoveries = employeerecoveries;
    }
    public Integer getNthinstallment() {
        return this.nthinstallment;
    }
    
    public void setNthinstallment(Integer nthinstallment) {
        this.nthinstallment = nthinstallment;
    }
    public BigDecimal getInstallmentamount() {
        return this.installmentamount;
    }
    
    public void setInstallmentamount(BigDecimal installmentamount) {
        this.installmentamount = installmentamount;
    }
    public BigDecimal getLoanbalance() {
        return this.loanbalance;
    }
    
    public void setLoanbalance(BigDecimal loanbalance) {
        this.loanbalance = loanbalance;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


