package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Employeedesignation generated by hbm2java
 */
public class Employeedesignation  implements java.io.Serializable {


     private String id;
     private Employeemaster employeemaster;
     private Date periodfrom;
     private Date periodto;
     private String designationcode;
     private String regioncode;
     private String payscalecode;
     private String orderno;
     private byte[] ordercopy;
     private Boolean synchronized_;
     private String accregion;

    public Employeedesignation() {
    }

	
    public Employeedesignation(String id, Employeemaster employeemaster) {
        this.id = id;
        this.employeemaster = employeemaster;
    }
    public Employeedesignation(String id, Employeemaster employeemaster, Date periodfrom, Date periodto, String designationcode, String regioncode, String payscalecode, String orderno, byte[] ordercopy, Boolean synchronized_, String accregion) {
       this.id = id;
       this.employeemaster = employeemaster;
       this.periodfrom = periodfrom;
       this.periodto = periodto;
       this.designationcode = designationcode;
       this.regioncode = regioncode;
       this.payscalecode = payscalecode;
       this.orderno = orderno;
       this.ordercopy = ordercopy;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Date getPeriodfrom() {
        return this.periodfrom;
    }
    
    public void setPeriodfrom(Date periodfrom) {
        this.periodfrom = periodfrom;
    }
    public Date getPeriodto() {
        return this.periodto;
    }
    
    public void setPeriodto(Date periodto) {
        this.periodto = periodto;
    }
    public String getDesignationcode() {
        return this.designationcode;
    }
    
    public void setDesignationcode(String designationcode) {
        this.designationcode = designationcode;
    }
    public String getRegioncode() {
        return this.regioncode;
    }
    
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }
    public String getPayscalecode() {
        return this.payscalecode;
    }
    
    public void setPayscalecode(String payscalecode) {
        this.payscalecode = payscalecode;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public byte[] getOrdercopy() {
        return this.ordercopy;
    }
    
    public void setOrdercopy(byte[] ordercopy) {
        this.ordercopy = ordercopy;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }




}


