package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Employeeearningsdetails generated by hbm2java
 */
public class Employeeearningsdetails  implements java.io.Serializable {


     private String id;
     private Salarystructure salarystructure;
     private String earningmasterid;
     private BigDecimal amount;
     private BigDecimal percentage;
     private Boolean ispercentage;
     private Boolean cancelled;
     private String accregion;

    public Employeeearningsdetails() {
    }

	
    public Employeeearningsdetails(String id) {
        this.id = id;
    }
    public Employeeearningsdetails(String id, Salarystructure salarystructure, String earningmasterid, BigDecimal amount, BigDecimal percentage, Boolean ispercentage, Boolean cancelled, String accregion) {
       this.id = id;
       this.salarystructure = salarystructure;
       this.earningmasterid = earningmasterid;
       this.amount = amount;
       this.percentage = percentage;
       this.ispercentage = ispercentage;
       this.cancelled = cancelled;
       this.accregion = accregion;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Salarystructure getSalarystructure() {
        return this.salarystructure;
    }
    
    public void setSalarystructure(Salarystructure salarystructure) {
        this.salarystructure = salarystructure;
    }
    public String getEarningmasterid() {
        return this.earningmasterid;
    }
    
    public void setEarningmasterid(String earningmasterid) {
        this.earningmasterid = earningmasterid;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public Boolean getIspercentage() {
        return this.ispercentage;
    }
    
    public void setIspercentage(Boolean ispercentage) {
        this.ispercentage = ispercentage;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }




}


