package com.onward.persistence.payroll;
// Generated 8 Jun, 2015 10:40:08 AM by Hibernate Tools 3.2.1.GA



/**
 * EmployeedetailsId generated by hbm2java
 */
public class EmployeedetailsId  implements java.io.Serializable {


     private String epfno;
     private String categorytype;
     private int serialno;

    public EmployeedetailsId() {
    }

    public EmployeedetailsId(String epfno, String categorytype, int serialno) {
       this.epfno = epfno;
       this.categorytype = categorytype;
       this.serialno = serialno;
    }
   
    public String getEpfno() {
        return this.epfno;
    }
    
    public void setEpfno(String epfno) {
        this.epfno = epfno;
    }
    public String getCategorytype() {
        return this.categorytype;
    }
    
    public void setCategorytype(String categorytype) {
        this.categorytype = categorytype;
    }
    public int getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(int serialno) {
        this.serialno = serialno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployeedetailsId) ) return false;
		 EmployeedetailsId castOther = ( EmployeedetailsId ) other; 
         
		 return ( (this.getEpfno()==castOther.getEpfno()) || ( this.getEpfno()!=null && castOther.getEpfno()!=null && this.getEpfno().equals(castOther.getEpfno()) ) )
 && ( (this.getCategorytype()==castOther.getCategorytype()) || ( this.getCategorytype()!=null && castOther.getCategorytype()!=null && this.getCategorytype().equals(castOther.getCategorytype()) ) )
 && (this.getSerialno()==castOther.getSerialno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEpfno() == null ? 0 : this.getEpfno().hashCode() );
         result = 37 * result + ( getCategorytype() == null ? 0 : this.getCategorytype().hashCode() );
         result = 37 * result + this.getSerialno();
         return result;
   }   


}


