package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Employeedeductionaccountcode generated by hbm2java
 */
public class Employeedeductionaccountcode  implements java.io.Serializable {


     private String id;
     private Paycodemaster paycodemaster;
     private Employeemaster employeemaster;
     private String deductionaccountcode;
     private String createdby;
     private Date createddate;

    public Employeedeductionaccountcode() {
    }

	
    public Employeedeductionaccountcode(String id, Paycodemaster paycodemaster) {
        this.id = id;
        this.paycodemaster = paycodemaster;
    }
    public Employeedeductionaccountcode(String id, Paycodemaster paycodemaster, Employeemaster employeemaster, String deductionaccountcode, String createdby, Date createddate) {
       this.id = id;
       this.paycodemaster = paycodemaster;
       this.employeemaster = employeemaster;
       this.deductionaccountcode = deductionaccountcode;
       this.createdby = createdby;
       this.createddate = createddate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Paycodemaster getPaycodemaster() {
        return this.paycodemaster;
    }
    
    public void setPaycodemaster(Paycodemaster paycodemaster) {
        this.paycodemaster = paycodemaster;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public String getDeductionaccountcode() {
        return this.deductionaccountcode;
    }
    
    public void setDeductionaccountcode(String deductionaccountcode) {
        this.deductionaccountcode = deductionaccountcode;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


