package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employeemaster generated by hbm2java
 */
public class Employeemaster  implements java.io.Serializable {


     private String epfno;
     private String fpfno;
     private String employeename;
     private String fathername;
     private String gender;
     private Date dateofbirth;
     private Date dateofappoinment;
     private Date dateofprobation;
     private Date dateofconfirmation;
     private String region;
     private String section;
     private String designation;
     private String createdby;
     private Date createddate;
     private String empSta;
     private String paymentmode;
     private String banksbaccount;
     private String bankcode;
     private String pancardno;
     private String community;
     private Date eslp;
     private String employeecode;
     private boolean process;
     private int serialno;
     private Boolean synchronized_;
     private String category;
     private String subsection;
     private String nativeregion;
     private Date currentpositionjoindate;
     private String currentpositionjointime;
     private Set employeeprovidentfundotherses = new HashSet(0);
     private Set salarystructureactuals = new HashSet(0);
     private Set surrenderbills = new HashSet(0);
     private Set miscdeductionses = new HashSet(0);
     private Set employeetransferhistories = new HashSet(0);
     private Set stoppayrolldetailses = new HashSet(0);
     private Set salarydeductionotherses = new HashSet(0);
     private Set employeerecoverieses = new HashSet(0);
     private Set employeeattendances = new HashSet(0);
     private Set payrollprocessingdetailses = new HashSet(0);
     private Set employeedeductionaccountcodes = new HashSet(0);
     private Set employeedesignations = new HashSet(0);
     private Set salarystructures = new HashSet(0);
     private Set usermasters = new HashSet(0);
     private Set supplementatypaybills = new HashSet(0);
     private Set employeeloansandadvanceses = new HashSet(0);

    public Employeemaster() {
    }

	
    public Employeemaster(String epfno, boolean process, int serialno) {
        this.epfno = epfno;
        this.process = process;
        this.serialno = serialno;
    }
    public Employeemaster(String epfno, String fpfno, String employeename, String fathername, String gender, Date dateofbirth, Date dateofappoinment, Date dateofprobation, Date dateofconfirmation, String region, String section, String designation, String createdby, Date createddate, String empSta, String paymentmode, String banksbaccount, String bankcode, String pancardno, String community, Date eslp, String employeecode, boolean process, int serialno, Boolean synchronized_, String category, String subsection, String nativeregion, Date currentpositionjoindate, String currentpositionjointime, Set employeeprovidentfundotherses, Set salarystructureactuals, Set surrenderbills, Set miscdeductionses, Set employeetransferhistories, Set stoppayrolldetailses, Set salarydeductionotherses, Set employeerecoverieses, Set employeeattendances, Set payrollprocessingdetailses, Set employeedeductionaccountcodes, Set employeedesignations, Set salarystructures, Set usermasters, Set supplementatypaybills, Set employeeloansandadvanceses) {
       this.epfno = epfno;
       this.fpfno = fpfno;
       this.employeename = employeename;
       this.fathername = fathername;
       this.gender = gender;
       this.dateofbirth = dateofbirth;
       this.dateofappoinment = dateofappoinment;
       this.dateofprobation = dateofprobation;
       this.dateofconfirmation = dateofconfirmation;
       this.region = region;
       this.section = section;
       this.designation = designation;
       this.createdby = createdby;
       this.createddate = createddate;
       this.empSta = empSta;
       this.paymentmode = paymentmode;
       this.banksbaccount = banksbaccount;
       this.bankcode = bankcode;
       this.pancardno = pancardno;
       this.community = community;
       this.eslp = eslp;
       this.employeecode = employeecode;
       this.process = process;
       this.serialno = serialno;
       this.synchronized_ = synchronized_;
       this.category = category;
       this.subsection = subsection;
       this.nativeregion = nativeregion;
       this.currentpositionjoindate = currentpositionjoindate;
       this.currentpositionjointime = currentpositionjointime;
       this.employeeprovidentfundotherses = employeeprovidentfundotherses;
       this.salarystructureactuals = salarystructureactuals;
       this.surrenderbills = surrenderbills;
       this.miscdeductionses = miscdeductionses;
       this.employeetransferhistories = employeetransferhistories;
       this.stoppayrolldetailses = stoppayrolldetailses;
       this.salarydeductionotherses = salarydeductionotherses;
       this.employeerecoverieses = employeerecoverieses;
       this.employeeattendances = employeeattendances;
       this.payrollprocessingdetailses = payrollprocessingdetailses;
       this.employeedeductionaccountcodes = employeedeductionaccountcodes;
       this.employeedesignations = employeedesignations;
       this.salarystructures = salarystructures;
       this.usermasters = usermasters;
       this.supplementatypaybills = supplementatypaybills;
       this.employeeloansandadvanceses = employeeloansandadvanceses;
    }
   
    public String getEpfno() {
        return this.epfno;
    }
    
    public void setEpfno(String epfno) {
        this.epfno = epfno;
    }
    public String getFpfno() {
        return this.fpfno;
    }
    
    public void setFpfno(String fpfno) {
        this.fpfno = fpfno;
    }
    public String getEmployeename() {
        return this.employeename;
    }
    
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }
    public String getFathername() {
        return this.fathername;
    }
    
    public void setFathername(String fathername) {
        this.fathername = fathername;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDateofbirth() {
        return this.dateofbirth;
    }
    
    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }
    public Date getDateofappoinment() {
        return this.dateofappoinment;
    }
    
    public void setDateofappoinment(Date dateofappoinment) {
        this.dateofappoinment = dateofappoinment;
    }
    public Date getDateofprobation() {
        return this.dateofprobation;
    }
    
    public void setDateofprobation(Date dateofprobation) {
        this.dateofprobation = dateofprobation;
    }
    public Date getDateofconfirmation() {
        return this.dateofconfirmation;
    }
    
    public void setDateofconfirmation(Date dateofconfirmation) {
        this.dateofconfirmation = dateofconfirmation;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getEmpSta() {
        return this.empSta;
    }
    
    public void setEmpSta(String empSta) {
        this.empSta = empSta;
    }
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }
    public String getBanksbaccount() {
        return this.banksbaccount;
    }
    
    public void setBanksbaccount(String banksbaccount) {
        this.banksbaccount = banksbaccount;
    }
    public String getBankcode() {
        return this.bankcode;
    }
    
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }
    public String getPancardno() {
        return this.pancardno;
    }
    
    public void setPancardno(String pancardno) {
        this.pancardno = pancardno;
    }
    public String getCommunity() {
        return this.community;
    }
    
    public void setCommunity(String community) {
        this.community = community;
    }
    public Date getEslp() {
        return this.eslp;
    }
    
    public void setEslp(Date eslp) {
        this.eslp = eslp;
    }
    public String getEmployeecode() {
        return this.employeecode;
    }
    
    public void setEmployeecode(String employeecode) {
        this.employeecode = employeecode;
    }
    public boolean isProcess() {
        return this.process;
    }
    
    public void setProcess(boolean process) {
        this.process = process;
    }
    public int getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(int serialno) {
        this.serialno = serialno;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getSubsection() {
        return this.subsection;
    }
    
    public void setSubsection(String subsection) {
        this.subsection = subsection;
    }
    public String getNativeregion() {
        return this.nativeregion;
    }
    
    public void setNativeregion(String nativeregion) {
        this.nativeregion = nativeregion;
    }
    public Date getCurrentpositionjoindate() {
        return this.currentpositionjoindate;
    }
    
    public void setCurrentpositionjoindate(Date currentpositionjoindate) {
        this.currentpositionjoindate = currentpositionjoindate;
    }
    public String getCurrentpositionjointime() {
        return this.currentpositionjointime;
    }
    
    public void setCurrentpositionjointime(String currentpositionjointime) {
        this.currentpositionjointime = currentpositionjointime;
    }
    public Set getEmployeeprovidentfundotherses() {
        return this.employeeprovidentfundotherses;
    }
    
    public void setEmployeeprovidentfundotherses(Set employeeprovidentfundotherses) {
        this.employeeprovidentfundotherses = employeeprovidentfundotherses;
    }
    public Set getSalarystructureactuals() {
        return this.salarystructureactuals;
    }
    
    public void setSalarystructureactuals(Set salarystructureactuals) {
        this.salarystructureactuals = salarystructureactuals;
    }
    public Set getSurrenderbills() {
        return this.surrenderbills;
    }
    
    public void setSurrenderbills(Set surrenderbills) {
        this.surrenderbills = surrenderbills;
    }
    public Set getMiscdeductionses() {
        return this.miscdeductionses;
    }
    
    public void setMiscdeductionses(Set miscdeductionses) {
        this.miscdeductionses = miscdeductionses;
    }
    public Set getEmployeetransferhistories() {
        return this.employeetransferhistories;
    }
    
    public void setEmployeetransferhistories(Set employeetransferhistories) {
        this.employeetransferhistories = employeetransferhistories;
    }
    public Set getStoppayrolldetailses() {
        return this.stoppayrolldetailses;
    }
    
    public void setStoppayrolldetailses(Set stoppayrolldetailses) {
        this.stoppayrolldetailses = stoppayrolldetailses;
    }
    public Set getSalarydeductionotherses() {
        return this.salarydeductionotherses;
    }
    
    public void setSalarydeductionotherses(Set salarydeductionotherses) {
        this.salarydeductionotherses = salarydeductionotherses;
    }
    public Set getEmployeerecoverieses() {
        return this.employeerecoverieses;
    }
    
    public void setEmployeerecoverieses(Set employeerecoverieses) {
        this.employeerecoverieses = employeerecoverieses;
    }
    public Set getEmployeeattendances() {
        return this.employeeattendances;
    }
    
    public void setEmployeeattendances(Set employeeattendances) {
        this.employeeattendances = employeeattendances;
    }
    public Set getPayrollprocessingdetailses() {
        return this.payrollprocessingdetailses;
    }
    
    public void setPayrollprocessingdetailses(Set payrollprocessingdetailses) {
        this.payrollprocessingdetailses = payrollprocessingdetailses;
    }
    public Set getEmployeedeductionaccountcodes() {
        return this.employeedeductionaccountcodes;
    }
    
    public void setEmployeedeductionaccountcodes(Set employeedeductionaccountcodes) {
        this.employeedeductionaccountcodes = employeedeductionaccountcodes;
    }
    public Set getEmployeedesignations() {
        return this.employeedesignations;
    }
    
    public void setEmployeedesignations(Set employeedesignations) {
        this.employeedesignations = employeedesignations;
    }
    public Set getSalarystructures() {
        return this.salarystructures;
    }
    
    public void setSalarystructures(Set salarystructures) {
        this.salarystructures = salarystructures;
    }
    public Set getUsermasters() {
        return this.usermasters;
    }
    
    public void setUsermasters(Set usermasters) {
        this.usermasters = usermasters;
    }
    public Set getSupplementatypaybills() {
        return this.supplementatypaybills;
    }
    
    public void setSupplementatypaybills(Set supplementatypaybills) {
        this.supplementatypaybills = supplementatypaybills;
    }
    public Set getEmployeeloansandadvanceses() {
        return this.employeeloansandadvanceses;
    }
    
    public void setEmployeeloansandadvanceses(Set employeeloansandadvanceses) {
        this.employeeloansandadvanceses = employeeloansandadvanceses;
    }




}


