package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Epfloantypes generated by hbm2java
 */
public class Epfloantypes  implements java.io.Serializable {


     private String id;
     private String name;
     private String rptgroup;
     private Set epfloanapplications = new HashSet(0);

    public Epfloantypes() {
    }

	
    public Epfloantypes(String id) {
        this.id = id;
    }
    public Epfloantypes(String id, String name, String rptgroup, Set epfloanapplications) {
       this.id = id;
       this.name = name;
       this.rptgroup = rptgroup;
       this.epfloanapplications = epfloanapplications;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRptgroup() {
        return this.rptgroup;
    }
    
    public void setRptgroup(String rptgroup) {
        this.rptgroup = rptgroup;
    }
    public Set getEpfloanapplications() {
        return this.epfloanapplications;
    }
    
    public void setEpfloanapplications(Set epfloanapplications) {
        this.epfloanapplications = epfloanapplications;
    }




}


