package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Epfloanapplication generated by hbm2java
 */
public class Epfloanapplication  implements java.io.Serializable {


     private String id;
     private Employeeepfmaster employeeepfmaster;
     private Accountingyear accountingyear;
     private Regionmaster regionmaster;
     private Epfloantypes epfloantypes;
     private BigDecimal loanamount;
     private Long month;
     private Long year;
     private Date date;
     private String tapalno;
     private Boolean isfinalsettlement;
     private String remarks;
     private BigDecimal approvedamount;
     private String status;
     private Long noofinstallment;

    public Epfloanapplication() {
    }

	
    public Epfloanapplication(String id) {
        this.id = id;
    }
    public Epfloanapplication(String id, Employeeepfmaster employeeepfmaster, Accountingyear accountingyear, Regionmaster regionmaster, Epfloantypes epfloantypes, BigDecimal loanamount, Long month, Long year, Date date, String tapalno, Boolean isfinalsettlement, String remarks, BigDecimal approvedamount, String status, Long noofinstallment) {
       this.id = id;
       this.employeeepfmaster = employeeepfmaster;
       this.accountingyear = accountingyear;
       this.regionmaster = regionmaster;
       this.epfloantypes = epfloantypes;
       this.loanamount = loanamount;
       this.month = month;
       this.year = year;
       this.date = date;
       this.tapalno = tapalno;
       this.isfinalsettlement = isfinalsettlement;
       this.remarks = remarks;
       this.approvedamount = approvedamount;
       this.status = status;
       this.noofinstallment = noofinstallment;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeeepfmaster getEmployeeepfmaster() {
        return this.employeeepfmaster;
    }
    
    public void setEmployeeepfmaster(Employeeepfmaster employeeepfmaster) {
        this.employeeepfmaster = employeeepfmaster;
    }
    public Accountingyear getAccountingyear() {
        return this.accountingyear;
    }
    
    public void setAccountingyear(Accountingyear accountingyear) {
        this.accountingyear = accountingyear;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public Epfloantypes getEpfloantypes() {
        return this.epfloantypes;
    }
    
    public void setEpfloantypes(Epfloantypes epfloantypes) {
        this.epfloantypes = epfloantypes;
    }
    public BigDecimal getLoanamount() {
        return this.loanamount;
    }
    
    public void setLoanamount(BigDecimal loanamount) {
        this.loanamount = loanamount;
    }
    public Long getMonth() {
        return this.month;
    }
    
    public void setMonth(Long month) {
        this.month = month;
    }
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTapalno() {
        return this.tapalno;
    }
    
    public void setTapalno(String tapalno) {
        this.tapalno = tapalno;
    }
    public Boolean getIsfinalsettlement() {
        return this.isfinalsettlement;
    }
    
    public void setIsfinalsettlement(Boolean isfinalsettlement) {
        this.isfinalsettlement = isfinalsettlement;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getApprovedamount() {
        return this.approvedamount;
    }
    
    public void setApprovedamount(BigDecimal approvedamount) {
        this.approvedamount = approvedamount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getNoofinstallment() {
        return this.noofinstallment;
    }
    
    public void setNoofinstallment(Long noofinstallment) {
        this.noofinstallment = noofinstallment;
    }




}


