package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Epfopeningbalance generated by hbm2java
 */
public class Epfopeningbalance  implements java.io.Serializable {


     private long id;
     private Employeeepfmaster employeeepfmaster;
     private Accountingyear accountingyear;
     private BigDecimal subscriptionOb;
     private BigDecimal contributionOb;
     private BigDecimal loanbalance;

    public Epfopeningbalance() {
    }

	
    public Epfopeningbalance(long id) {
        this.id = id;
    }
    public Epfopeningbalance(long id, Employeeepfmaster employeeepfmaster, Accountingyear accountingyear, BigDecimal subscriptionOb, BigDecimal contributionOb, BigDecimal loanbalance) {
       this.id = id;
       this.employeeepfmaster = employeeepfmaster;
       this.accountingyear = accountingyear;
       this.subscriptionOb = subscriptionOb;
       this.contributionOb = contributionOb;
       this.loanbalance = loanbalance;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Employeeepfmaster getEmployeeepfmaster() {
        return this.employeeepfmaster;
    }
    
    public void setEmployeeepfmaster(Employeeepfmaster employeeepfmaster) {
        this.employeeepfmaster = employeeepfmaster;
    }
    public Accountingyear getAccountingyear() {
        return this.accountingyear;
    }
    
    public void setAccountingyear(Accountingyear accountingyear) {
        this.accountingyear = accountingyear;
    }
    public BigDecimal getSubscriptionOb() {
        return this.subscriptionOb;
    }
    
    public void setSubscriptionOb(BigDecimal subscriptionOb) {
        this.subscriptionOb = subscriptionOb;
    }
    public BigDecimal getContributionOb() {
        return this.contributionOb;
    }
    
    public void setContributionOb(BigDecimal contributionOb) {
        this.contributionOb = contributionOb;
    }
    public BigDecimal getLoanbalance() {
        return this.loanbalance;
    }
    
    public void setLoanbalance(BigDecimal loanbalance) {
        this.loanbalance = loanbalance;
    }




}


