package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Incrementarrearreference generated by hbm2java
 */
public class Incrementarrearreference  implements java.io.Serializable {


     private String id;
     private String suppaybillid;
     private String type;
     private String processid;
     private String accregion;
     private Integer month;
     private Integer year;
     private Date createddate;
     private String createdby;
     private BigDecimal due;
     private BigDecimal arrear;
     private BigDecimal epf;
     private BigDecimal drawn;

    public Incrementarrearreference() {
    }

	
    public Incrementarrearreference(String id) {
        this.id = id;
    }
    public Incrementarrearreference(String id, String suppaybillid, String type, String processid, String accregion, Integer month, Integer year, Date createddate, String createdby, BigDecimal due, BigDecimal arrear, BigDecimal epf, BigDecimal drawn) {
       this.id = id;
       this.suppaybillid = suppaybillid;
       this.type = type;
       this.processid = processid;
       this.accregion = accregion;
       this.month = month;
       this.year = year;
       this.createddate = createddate;
       this.createdby = createdby;
       this.due = due;
       this.arrear = arrear;
       this.epf = epf;
       this.drawn = drawn;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSuppaybillid() {
        return this.suppaybillid;
    }
    
    public void setSuppaybillid(String suppaybillid) {
        this.suppaybillid = suppaybillid;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getProcessid() {
        return this.processid;
    }
    
    public void setProcessid(String processid) {
        this.processid = processid;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public BigDecimal getDue() {
        return this.due;
    }
    
    public void setDue(BigDecimal due) {
        this.due = due;
    }
    public BigDecimal getArrear() {
        return this.arrear;
    }
    
    public void setArrear(BigDecimal arrear) {
        this.arrear = arrear;
    }
    public BigDecimal getEpf() {
        return this.epf;
    }
    
    public void setEpf(BigDecimal epf) {
        this.epf = epf;
    }
    public BigDecimal getDrawn() {
        return this.drawn;
    }
    
    public void setDrawn(BigDecimal drawn) {
        this.drawn = drawn;
    }




}


