package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Interregionaccountsreconcil generated by hbm2java
 */
public class Interregionaccountsreconcil  implements java.io.Serializable {


     private String id;
     private Interregionaccounts interregionaccounts;
     private Voucherdetails voucherdetailsByVoucherdetailsdestination;
     private Voucherdetails voucherdetailsByVoucherdetailssource;
     private BigDecimal sourceamount;
     private BigDecimal destinationamount;
     private Boolean cancelled;

    public Interregionaccountsreconcil() {
    }

	
    public Interregionaccountsreconcil(String id) {
        this.id = id;
    }
    public Interregionaccountsreconcil(String id, Interregionaccounts interregionaccounts, Voucherdetails voucherdetailsByVoucherdetailsdestination, Voucherdetails voucherdetailsByVoucherdetailssource, BigDecimal sourceamount, BigDecimal destinationamount, Boolean cancelled) {
       this.id = id;
       this.interregionaccounts = interregionaccounts;
       this.voucherdetailsByVoucherdetailsdestination = voucherdetailsByVoucherdetailsdestination;
       this.voucherdetailsByVoucherdetailssource = voucherdetailsByVoucherdetailssource;
       this.sourceamount = sourceamount;
       this.destinationamount = destinationamount;
       this.cancelled = cancelled;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Interregionaccounts getInterregionaccounts() {
        return this.interregionaccounts;
    }
    
    public void setInterregionaccounts(Interregionaccounts interregionaccounts) {
        this.interregionaccounts = interregionaccounts;
    }
    public Voucherdetails getVoucherdetailsByVoucherdetailsdestination() {
        return this.voucherdetailsByVoucherdetailsdestination;
    }
    
    public void setVoucherdetailsByVoucherdetailsdestination(Voucherdetails voucherdetailsByVoucherdetailsdestination) {
        this.voucherdetailsByVoucherdetailsdestination = voucherdetailsByVoucherdetailsdestination;
    }
    public Voucherdetails getVoucherdetailsByVoucherdetailssource() {
        return this.voucherdetailsByVoucherdetailssource;
    }
    
    public void setVoucherdetailsByVoucherdetailssource(Voucherdetails voucherdetailsByVoucherdetailssource) {
        this.voucherdetailsByVoucherdetailssource = voucherdetailsByVoucherdetailssource;
    }
    public BigDecimal getSourceamount() {
        return this.sourceamount;
    }
    
    public void setSourceamount(BigDecimal sourceamount) {
        this.sourceamount = sourceamount;
    }
    public BigDecimal getDestinationamount() {
        return this.destinationamount;
    }
    
    public void setDestinationamount(BigDecimal destinationamount) {
        this.destinationamount = destinationamount;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }




}


