package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ledgermaster generated by hbm2java
 */
public class Ledgermaster  implements java.io.Serializable {


     private String id;
     private Ledgergroupmaster ledgergroupmaster;
     private String ledgername;
     private String grouporder;
     private boolean b5;
     private boolean b6;
     private boolean b7;
     private boolean b8;
     private Set budgetdetailses = new HashSet(0);
     private Set monthlyexpendituredetailses = new HashSet(0);
     private Set accountsheadses = new HashSet(0);

    public Ledgermaster() {
    }

	
    public Ledgermaster(String id, boolean b5, boolean b6, boolean b7, boolean b8) {
        this.id = id;
        this.b5 = b5;
        this.b6 = b6;
        this.b7 = b7;
        this.b8 = b8;
    }
    public Ledgermaster(String id, Ledgergroupmaster ledgergroupmaster, String ledgername, String grouporder, boolean b5, boolean b6, boolean b7, boolean b8, Set budgetdetailses, Set monthlyexpendituredetailses, Set accountsheadses) {
       this.id = id;
       this.ledgergroupmaster = ledgergroupmaster;
       this.ledgername = ledgername;
       this.grouporder = grouporder;
       this.b5 = b5;
       this.b6 = b6;
       this.b7 = b7;
       this.b8 = b8;
       this.budgetdetailses = budgetdetailses;
       this.monthlyexpendituredetailses = monthlyexpendituredetailses;
       this.accountsheadses = accountsheadses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Ledgergroupmaster getLedgergroupmaster() {
        return this.ledgergroupmaster;
    }
    
    public void setLedgergroupmaster(Ledgergroupmaster ledgergroupmaster) {
        this.ledgergroupmaster = ledgergroupmaster;
    }
    public String getLedgername() {
        return this.ledgername;
    }
    
    public void setLedgername(String ledgername) {
        this.ledgername = ledgername;
    }
    public String getGrouporder() {
        return this.grouporder;
    }
    
    public void setGrouporder(String grouporder) {
        this.grouporder = grouporder;
    }
    public boolean isB5() {
        return this.b5;
    }
    
    public void setB5(boolean b5) {
        this.b5 = b5;
    }
    public boolean isB6() {
        return this.b6;
    }
    
    public void setB6(boolean b6) {
        this.b6 = b6;
    }
    public boolean isB7() {
        return this.b7;
    }
    
    public void setB7(boolean b7) {
        this.b7 = b7;
    }
    public boolean isB8() {
        return this.b8;
    }
    
    public void setB8(boolean b8) {
        this.b8 = b8;
    }
    public Set getBudgetdetailses() {
        return this.budgetdetailses;
    }
    
    public void setBudgetdetailses(Set budgetdetailses) {
        this.budgetdetailses = budgetdetailses;
    }
    public Set getMonthlyexpendituredetailses() {
        return this.monthlyexpendituredetailses;
    }
    
    public void setMonthlyexpendituredetailses(Set monthlyexpendituredetailses) {
        this.monthlyexpendituredetailses = monthlyexpendituredetailses;
    }
    public Set getAccountsheadses() {
        return this.accountsheadses;
    }
    
    public void setAccountsheadses(Set accountsheadses) {
        this.accountsheadses = accountsheadses;
    }




}


