package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ledgergroupmaster generated by hbm2java
 */
public class Ledgergroupmaster  implements java.io.Serializable {


     private String id;
     private String ledgergroupname;
     private Set ledgermasters = new HashSet(0);

    public Ledgergroupmaster() {
    }

	
    public Ledgergroupmaster(String id) {
        this.id = id;
    }
    public Ledgergroupmaster(String id, String ledgergroupname, Set ledgermasters) {
       this.id = id;
       this.ledgergroupname = ledgergroupname;
       this.ledgermasters = ledgermasters;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getLedgergroupname() {
        return this.ledgergroupname;
    }
    
    public void setLedgergroupname(String ledgergroupname) {
        this.ledgergroupname = ledgergroupname;
    }
    public Set getLedgermasters() {
        return this.ledgermasters;
    }
    
    public void setLedgermasters(Set ledgermasters) {
        this.ledgermasters = ledgermasters;
    }




}


