package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Logincount generated by hbm2java
 */
public class Logincount  implements java.io.Serializable {


     private String userid;
     private Integer count;
     private Date logindate;
     private Date createddate;
     private String createdby;

    public Logincount() {
    }

	
    public Logincount(String userid) {
        this.userid = userid;
    }
    public Logincount(String userid, Integer count, Date logindate, Date createddate, String createdby) {
       this.userid = userid;
       this.count = count;
       this.logindate = logindate;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public Date getLogindate() {
        return this.logindate;
    }
    
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


