package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Menuprivilages generated by hbm2java
 */
public class Menuprivilages  implements java.io.Serializable {


     private String id;
     private Usertype usertype;
     private Menumaster menumaster;
     private Boolean accessright;

    public Menuprivilages() {
    }

	
    public Menuprivilages(String id, Usertype usertype, Menumaster menumaster) {
        this.id = id;
        this.usertype = usertype;
        this.menumaster = menumaster;
    }
    public Menuprivilages(String id, Usertype usertype, Menumaster menumaster, Boolean accessright) {
       this.id = id;
       this.usertype = usertype;
       this.menumaster = menumaster;
       this.accessright = accessright;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Usertype getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }
    public Menumaster getMenumaster() {
        return this.menumaster;
    }
    
    public void setMenumaster(Menumaster menumaster) {
        this.menumaster = menumaster;
    }
    public Boolean getAccessright() {
        return this.accessright;
    }
    
    public void setAccessright(Boolean accessright) {
        this.accessright = accessright;
    }




}


