package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Menumaster generated by hbm2java
 */
public class Menumaster  implements java.io.Serializable {


     private int code;
     private String actionname;
     private String methodname;
     private String labelname;
     private Integer parentcode;
     private Integer menuorder;
     private Boolean isvisible;
     private Character grouptype;
     private Set menuprivilageses = new HashSet(0);

    public Menumaster() {
    }

	
    public Menumaster(int code) {
        this.code = code;
    }
    public Menumaster(int code, String actionname, String methodname, String labelname, Integer parentcode, Integer menuorder, Boolean isvisible, Character grouptype, Set menuprivilageses) {
       this.code = code;
       this.actionname = actionname;
       this.methodname = methodname;
       this.labelname = labelname;
       this.parentcode = parentcode;
       this.menuorder = menuorder;
       this.isvisible = isvisible;
       this.grouptype = grouptype;
       this.menuprivilageses = menuprivilageses;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getActionname() {
        return this.actionname;
    }
    
    public void setActionname(String actionname) {
        this.actionname = actionname;
    }
    public String getMethodname() {
        return this.methodname;
    }
    
    public void setMethodname(String methodname) {
        this.methodname = methodname;
    }
    public String getLabelname() {
        return this.labelname;
    }
    
    public void setLabelname(String labelname) {
        this.labelname = labelname;
    }
    public Integer getParentcode() {
        return this.parentcode;
    }
    
    public void setParentcode(Integer parentcode) {
        this.parentcode = parentcode;
    }
    public Integer getMenuorder() {
        return this.menuorder;
    }
    
    public void setMenuorder(Integer menuorder) {
        this.menuorder = menuorder;
    }
    public Boolean getIsvisible() {
        return this.isvisible;
    }
    
    public void setIsvisible(Boolean isvisible) {
        this.isvisible = isvisible;
    }
    public Character getGrouptype() {
        return this.grouptype;
    }
    
    public void setGrouptype(Character grouptype) {
        this.grouptype = grouptype;
    }
    public Set getMenuprivilageses() {
        return this.menuprivilageses;
    }
    
    public void setMenuprivilageses(Set menuprivilageses) {
        this.menuprivilageses = menuprivilageses;
    }




}


