package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Miscdeductions generated by hbm2java
 */
public class Miscdeductions  implements java.io.Serializable {


     private String id;
     private Employeemaster employeemaster;
     private Integer year;
     private Integer month;
     private BigDecimal amount;
     private String deductionscode;
     private Boolean synchronized_;
     private String accregion;
     private String deductionaccountcode;
     private Date createddate;
     private String createdby;

    public Miscdeductions() {
    }

	
    public Miscdeductions(String id) {
        this.id = id;
    }
    public Miscdeductions(String id, Employeemaster employeemaster, Integer year, Integer month, BigDecimal amount, String deductionscode, Boolean synchronized_, String accregion, String deductionaccountcode, Date createddate, String createdby) {
       this.id = id;
       this.employeemaster = employeemaster;
       this.year = year;
       this.month = month;
       this.amount = amount;
       this.deductionscode = deductionscode;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
       this.deductionaccountcode = deductionaccountcode;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getDeductionscode() {
        return this.deductionscode;
    }
    
    public void setDeductionscode(String deductionscode) {
        this.deductionscode = deductionscode;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public String getDeductionaccountcode() {
        return this.deductionaccountcode;
    }
    
    public void setDeductionaccountcode(String deductionaccountcode) {
        this.deductionaccountcode = deductionaccountcode;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


