package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Monthlyexpendituredetails generated by hbm2java
 */
public class Monthlyexpendituredetails  implements java.io.Serializable {


     private String id;
     private Ledgermaster ledgermaster;
     private Budget budget;
     private Regionmaster regionmaster;
     private BigDecimal currentmonthbutget;
     private BigDecimal estimatedbudget;
     private BigDecimal balance;
     private BigDecimal fmaamount;
     private Integer month;
     private Integer year;
     private Date createddate;
     private String createdby;

    public Monthlyexpendituredetails() {
    }

	
    public Monthlyexpendituredetails(String id) {
        this.id = id;
    }
    public Monthlyexpendituredetails(String id, Ledgermaster ledgermaster, Budget budget, Regionmaster regionmaster, BigDecimal currentmonthbutget, BigDecimal estimatedbudget, BigDecimal balance, BigDecimal fmaamount, Integer month, Integer year, Date createddate, String createdby) {
       this.id = id;
       this.ledgermaster = ledgermaster;
       this.budget = budget;
       this.regionmaster = regionmaster;
       this.currentmonthbutget = currentmonthbutget;
       this.estimatedbudget = estimatedbudget;
       this.balance = balance;
       this.fmaamount = fmaamount;
       this.month = month;
       this.year = year;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Ledgermaster getLedgermaster() {
        return this.ledgermaster;
    }
    
    public void setLedgermaster(Ledgermaster ledgermaster) {
        this.ledgermaster = ledgermaster;
    }
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public BigDecimal getCurrentmonthbutget() {
        return this.currentmonthbutget;
    }
    
    public void setCurrentmonthbutget(BigDecimal currentmonthbutget) {
        this.currentmonthbutget = currentmonthbutget;
    }
    public BigDecimal getEstimatedbudget() {
        return this.estimatedbudget;
    }
    
    public void setEstimatedbudget(BigDecimal estimatedbudget) {
        this.estimatedbudget = estimatedbudget;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    public BigDecimal getFmaamount() {
        return this.fmaamount;
    }
    
    public void setFmaamount(BigDecimal fmaamount) {
        this.fmaamount = fmaamount;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


