package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Passwordhistory generated by hbm2java
 */
public class Passwordhistory  implements java.io.Serializable {


     private PasswordhistoryId id;
     private String username;
     private Integer userstatus;
     private Date nextpwddate;
     private byte[] encryptpassword;
     private byte[] secretekey;
     private String createdby;
     private Date createddate;
     private byte[] secretkey;
     private String epfno;
     private String usertypeid;

    public Passwordhistory() {
    }

	
    public Passwordhistory(PasswordhistoryId id) {
        this.id = id;
    }
    public Passwordhistory(PasswordhistoryId id, String username, Integer userstatus, Date nextpwddate, byte[] encryptpassword, byte[] secretekey, String createdby, Date createddate, byte[] secretkey, String epfno, String usertypeid) {
       this.id = id;
       this.username = username;
       this.userstatus = userstatus;
       this.nextpwddate = nextpwddate;
       this.encryptpassword = encryptpassword;
       this.secretekey = secretekey;
       this.createdby = createdby;
       this.createddate = createddate;
       this.secretkey = secretkey;
       this.epfno = epfno;
       this.usertypeid = usertypeid;
    }
   
    public PasswordhistoryId getId() {
        return this.id;
    }
    
    public void setId(PasswordhistoryId id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getUserstatus() {
        return this.userstatus;
    }
    
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }
    public Date getNextpwddate() {
        return this.nextpwddate;
    }
    
    public void setNextpwddate(Date nextpwddate) {
        this.nextpwddate = nextpwddate;
    }
    public byte[] getEncryptpassword() {
        return this.encryptpassword;
    }
    
    public void setEncryptpassword(byte[] encryptpassword) {
        this.encryptpassword = encryptpassword;
    }
    public byte[] getSecretekey() {
        return this.secretekey;
    }
    
    public void setSecretekey(byte[] secretekey) {
        this.secretekey = secretekey;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public byte[] getSecretkey() {
        return this.secretkey;
    }
    
    public void setSecretkey(byte[] secretkey) {
        this.secretkey = secretkey;
    }
    public String getEpfno() {
        return this.epfno;
    }
    
    public void setEpfno(String epfno) {
        this.epfno = epfno;
    }
    public String getUsertypeid() {
        return this.usertypeid;
    }
    
    public void setUsertypeid(String usertypeid) {
        this.usertypeid = usertypeid;
    }




}


