package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PasswordhistoryId generated by hbm2java
 */
public class PasswordhistoryId  implements java.io.Serializable {


     private String userid;
     private int sequencenumber;

    public PasswordhistoryId() {
    }

    public PasswordhistoryId(String userid, int sequencenumber) {
       this.userid = userid;
       this.sequencenumber = sequencenumber;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public int getSequencenumber() {
        return this.sequencenumber;
    }
    
    public void setSequencenumber(int sequencenumber) {
        this.sequencenumber = sequencenumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PasswordhistoryId) ) return false;
		 PasswordhistoryId castOther = ( PasswordhistoryId ) other; 
         
		 return ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
 && (this.getSequencenumber()==castOther.getSequencenumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
         result = 37 * result + this.getSequencenumber();
         return result;
   }   


}


