package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Paycodemaster generated by hbm2java
 */
public class Paycodemaster  implements java.io.Serializable {


     private String paycode;
     private String paycodename;
     private Character paycodetype;
     private BigDecimal paypercentage;
     private Boolean synchronized_;
     private String grouphead;
     private String paycodeserial;
     private Set employeedeductionaccountcodes = new HashSet(0);
     private Set salarydeductionotherses = new HashSet(0);
     private Set ccahras = new HashSet(0);

    public Paycodemaster() {
    }

	
    public Paycodemaster(String paycode) {
        this.paycode = paycode;
    }
    public Paycodemaster(String paycode, String paycodename, Character paycodetype, BigDecimal paypercentage, Boolean synchronized_, String grouphead, String paycodeserial, Set employeedeductionaccountcodes, Set salarydeductionotherses, Set ccahras) {
       this.paycode = paycode;
       this.paycodename = paycodename;
       this.paycodetype = paycodetype;
       this.paypercentage = paypercentage;
       this.synchronized_ = synchronized_;
       this.grouphead = grouphead;
       this.paycodeserial = paycodeserial;
       this.employeedeductionaccountcodes = employeedeductionaccountcodes;
       this.salarydeductionotherses = salarydeductionotherses;
       this.ccahras = ccahras;
    }
   
    public String getPaycode() {
        return this.paycode;
    }
    
    public void setPaycode(String paycode) {
        this.paycode = paycode;
    }
    public String getPaycodename() {
        return this.paycodename;
    }
    
    public void setPaycodename(String paycodename) {
        this.paycodename = paycodename;
    }
    public Character getPaycodetype() {
        return this.paycodetype;
    }
    
    public void setPaycodetype(Character paycodetype) {
        this.paycodetype = paycodetype;
    }
    public BigDecimal getPaypercentage() {
        return this.paypercentage;
    }
    
    public void setPaypercentage(BigDecimal paypercentage) {
        this.paypercentage = paypercentage;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getGrouphead() {
        return this.grouphead;
    }
    
    public void setGrouphead(String grouphead) {
        this.grouphead = grouphead;
    }
    public String getPaycodeserial() {
        return this.paycodeserial;
    }
    
    public void setPaycodeserial(String paycodeserial) {
        this.paycodeserial = paycodeserial;
    }
    public Set getEmployeedeductionaccountcodes() {
        return this.employeedeductionaccountcodes;
    }
    
    public void setEmployeedeductionaccountcodes(Set employeedeductionaccountcodes) {
        this.employeedeductionaccountcodes = employeedeductionaccountcodes;
    }
    public Set getSalarydeductionotherses() {
        return this.salarydeductionotherses;
    }
    
    public void setSalarydeductionotherses(Set salarydeductionotherses) {
        this.salarydeductionotherses = salarydeductionotherses;
    }
    public Set getCcahras() {
        return this.ccahras;
    }
    
    public void setCcahras(Set ccahras) {
        this.ccahras = ccahras;
    }




}


