package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Paymentmode generated by hbm2java
 */
public class Paymentmode  implements java.io.Serializable {


     private String code;
     private String type;
     private Set receiptpaymentdetailses = new HashSet(0);
     private Set receiptpaymentdetailshistories = new HashSet(0);

    public Paymentmode() {
    }

	
    public Paymentmode(String code) {
        this.code = code;
    }
    public Paymentmode(String code, String type, Set receiptpaymentdetailses, Set receiptpaymentdetailshistories) {
       this.code = code;
       this.type = type;
       this.receiptpaymentdetailses = receiptpaymentdetailses;
       this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getReceiptpaymentdetailses() {
        return this.receiptpaymentdetailses;
    }
    
    public void setReceiptpaymentdetailses(Set receiptpaymentdetailses) {
        this.receiptpaymentdetailses = receiptpaymentdetailses;
    }
    public Set getReceiptpaymentdetailshistories() {
        return this.receiptpaymentdetailshistories;
    }
    
    public void setReceiptpaymentdetailshistories(Set receiptpaymentdetailshistories) {
        this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }




}


