package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Payrollvoucher generated by hbm2java
 */
public class Payrollvoucher  implements java.io.Serializable {


     private String id;
     private Payrollvouchercategory payrollvouchercategory;
     private Integer payrollmonth;
     private Integer payrollyear;
     private String voucherno;

    public Payrollvoucher() {
    }

	
    public Payrollvoucher(String id) {
        this.id = id;
    }
    public Payrollvoucher(String id, Payrollvouchercategory payrollvouchercategory, Integer payrollmonth, Integer payrollyear, String voucherno) {
       this.id = id;
       this.payrollvouchercategory = payrollvouchercategory;
       this.payrollmonth = payrollmonth;
       this.payrollyear = payrollyear;
       this.voucherno = voucherno;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Payrollvouchercategory getPayrollvouchercategory() {
        return this.payrollvouchercategory;
    }
    
    public void setPayrollvouchercategory(Payrollvouchercategory payrollvouchercategory) {
        this.payrollvouchercategory = payrollvouchercategory;
    }
    public Integer getPayrollmonth() {
        return this.payrollmonth;
    }
    
    public void setPayrollmonth(Integer payrollmonth) {
        this.payrollmonth = payrollmonth;
    }
    public Integer getPayrollyear() {
        return this.payrollyear;
    }
    
    public void setPayrollyear(Integer payrollyear) {
        this.payrollyear = payrollyear;
    }
    public String getVoucherno() {
        return this.voucherno;
    }
    
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }




}


