package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Payrollvouchercategory generated by hbm2java
 */
public class Payrollvouchercategory  implements java.io.Serializable {


     private int id;
     private String category;
     private Set payrollvouchers = new HashSet(0);

    public Payrollvouchercategory() {
    }

	
    public Payrollvouchercategory(int id) {
        this.id = id;
    }
    public Payrollvouchercategory(int id, String category, Set payrollvouchers) {
       this.id = id;
       this.category = category;
       this.payrollvouchers = payrollvouchers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Set getPayrollvouchers() {
        return this.payrollvouchers;
    }
    
    public void setPayrollvouchers(Set payrollvouchers) {
        this.payrollvouchers = payrollvouchers;
    }




}


