package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payrollprocessingdetails generated by hbm2java
 */
public class Payrollprocessingdetails  implements java.io.Serializable {


     private String id;
     private Employeemaster employeemaster;
     private Date startdate;
     private Date enddate;
     private Short workingday;
     private Short workedday;
     private Long leaveeligible;
     private Short leaveavailed;
     private Boolean process;
     private Boolean processedregular;
     private Integer year;
     private Integer month;
     private String salarystructureid;
     private String payrollprocessingid;
     private Boolean synchronized_;
     private String accregion;
     private Integer salarydays;
     private String remarks;
     private String paymentmode;
     private String section;
     private String subsection;
     private String employeecategory;
     private String designation;
     private Date createddate;
     private String createdby;
     private Set employeeearningstransactionses = new HashSet(0);
     private Set employeerecoverydetailses = new HashSet(0);
     private Set employeedeductionstransactionses = new HashSet(0);
     private Set employeeloansandadvancesdetailses = new HashSet(0);

    public Payrollprocessingdetails() {
    }

	
    public Payrollprocessingdetails(String id) {
        this.id = id;
    }
    public Payrollprocessingdetails(String id, Employeemaster employeemaster, Date startdate, Date enddate, Short workingday, Short workedday, Long leaveeligible, Short leaveavailed, Boolean process, Boolean processedregular, Integer year, Integer month, String salarystructureid, String payrollprocessingid, Boolean synchronized_, String accregion, Integer salarydays, String remarks, String paymentmode, String section, String subsection, String employeecategory, String designation, Date createddate, String createdby, Set employeeearningstransactionses, Set employeerecoverydetailses, Set employeedeductionstransactionses, Set employeeloansandadvancesdetailses) {
       this.id = id;
       this.employeemaster = employeemaster;
       this.startdate = startdate;
       this.enddate = enddate;
       this.workingday = workingday;
       this.workedday = workedday;
       this.leaveeligible = leaveeligible;
       this.leaveavailed = leaveavailed;
       this.process = process;
       this.processedregular = processedregular;
       this.year = year;
       this.month = month;
       this.salarystructureid = salarystructureid;
       this.payrollprocessingid = payrollprocessingid;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
       this.salarydays = salarydays;
       this.remarks = remarks;
       this.paymentmode = paymentmode;
       this.section = section;
       this.subsection = subsection;
       this.employeecategory = employeecategory;
       this.designation = designation;
       this.createddate = createddate;
       this.createdby = createdby;
       this.employeeearningstransactionses = employeeearningstransactionses;
       this.employeerecoverydetailses = employeerecoverydetailses;
       this.employeedeductionstransactionses = employeedeductionstransactionses;
       this.employeeloansandadvancesdetailses = employeeloansandadvancesdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Short getWorkingday() {
        return this.workingday;
    }
    
    public void setWorkingday(Short workingday) {
        this.workingday = workingday;
    }
    public Short getWorkedday() {
        return this.workedday;
    }
    
    public void setWorkedday(Short workedday) {
        this.workedday = workedday;
    }
    public Long getLeaveeligible() {
        return this.leaveeligible;
    }
    
    public void setLeaveeligible(Long leaveeligible) {
        this.leaveeligible = leaveeligible;
    }
    public Short getLeaveavailed() {
        return this.leaveavailed;
    }
    
    public void setLeaveavailed(Short leaveavailed) {
        this.leaveavailed = leaveavailed;
    }
    public Boolean getProcess() {
        return this.process;
    }
    
    public void setProcess(Boolean process) {
        this.process = process;
    }
    public Boolean getProcessedregular() {
        return this.processedregular;
    }
    
    public void setProcessedregular(Boolean processedregular) {
        this.processedregular = processedregular;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public String getSalarystructureid() {
        return this.salarystructureid;
    }
    
    public void setSalarystructureid(String salarystructureid) {
        this.salarystructureid = salarystructureid;
    }
    public String getPayrollprocessingid() {
        return this.payrollprocessingid;
    }
    
    public void setPayrollprocessingid(String payrollprocessingid) {
        this.payrollprocessingid = payrollprocessingid;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Integer getSalarydays() {
        return this.salarydays;
    }
    
    public void setSalarydays(Integer salarydays) {
        this.salarydays = salarydays;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getSubsection() {
        return this.subsection;
    }
    
    public void setSubsection(String subsection) {
        this.subsection = subsection;
    }
    public String getEmployeecategory() {
        return this.employeecategory;
    }
    
    public void setEmployeecategory(String employeecategory) {
        this.employeecategory = employeecategory;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Set getEmployeeearningstransactionses() {
        return this.employeeearningstransactionses;
    }
    
    public void setEmployeeearningstransactionses(Set employeeearningstransactionses) {
        this.employeeearningstransactionses = employeeearningstransactionses;
    }
    public Set getEmployeerecoverydetailses() {
        return this.employeerecoverydetailses;
    }
    
    public void setEmployeerecoverydetailses(Set employeerecoverydetailses) {
        this.employeerecoverydetailses = employeerecoverydetailses;
    }
    public Set getEmployeedeductionstransactionses() {
        return this.employeedeductionstransactionses;
    }
    
    public void setEmployeedeductionstransactionses(Set employeedeductionstransactionses) {
        this.employeedeductionstransactionses = employeedeductionstransactionses;
    }
    public Set getEmployeeloansandadvancesdetailses() {
        return this.employeeloansandadvancesdetailses;
    }
    
    public void setEmployeeloansandadvancesdetailses(Set employeeloansandadvancesdetailses) {
        this.employeeloansandadvancesdetailses = employeeloansandadvancesdetailses;
    }




}


