package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Payrollprocessing generated by hbm2java
 */
public class Payrollprocessing  implements java.io.Serializable {


     private String id;
     private Regionmaster regionmaster;
     private Integer month;
     private Integer year;
     private Boolean isopen;
     private Boolean synchronized_;
     private String accregion;
     private Date createddate;
     private String createdby;

    public Payrollprocessing() {
    }

	
    public Payrollprocessing(String id) {
        this.id = id;
    }
    public Payrollprocessing(String id, Regionmaster regionmaster, Integer month, Integer year, Boolean isopen, Boolean synchronized_, String accregion, Date createddate, String createdby) {
       this.id = id;
       this.regionmaster = regionmaster;
       this.month = month;
       this.year = year;
       this.isopen = isopen;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Boolean getIsopen() {
        return this.isopen;
    }
    
    public void setIsopen(Boolean isopen) {
        this.isopen = isopen;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


