package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Payscalemaster generated by hbm2java
 */
public class Payscalemaster  implements java.io.Serializable {


     private String payscalecode;
     private String payscaledescription;
     private BigDecimal basicpay;
     private BigDecimal annualincrement;
     private BigDecimal finalbasicpay;
     private Date periodfrom;
     private Date periodto;
     private String empearningscode;
     private String empdeductionscode;
     private Boolean synchronized_;
     private String accregion;

    public Payscalemaster() {
    }

	
    public Payscalemaster(String payscalecode) {
        this.payscalecode = payscalecode;
    }
    public Payscalemaster(String payscalecode, String payscaledescription, BigDecimal basicpay, BigDecimal annualincrement, BigDecimal finalbasicpay, Date periodfrom, Date periodto, String empearningscode, String empdeductionscode, Boolean synchronized_, String accregion) {
       this.payscalecode = payscalecode;
       this.payscaledescription = payscaledescription;
       this.basicpay = basicpay;
       this.annualincrement = annualincrement;
       this.finalbasicpay = finalbasicpay;
       this.periodfrom = periodfrom;
       this.periodto = periodto;
       this.empearningscode = empearningscode;
       this.empdeductionscode = empdeductionscode;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
    }
   
    public String getPayscalecode() {
        return this.payscalecode;
    }
    
    public void setPayscalecode(String payscalecode) {
        this.payscalecode = payscalecode;
    }
    public String getPayscaledescription() {
        return this.payscaledescription;
    }
    
    public void setPayscaledescription(String payscaledescription) {
        this.payscaledescription = payscaledescription;
    }
    public BigDecimal getBasicpay() {
        return this.basicpay;
    }
    
    public void setBasicpay(BigDecimal basicpay) {
        this.basicpay = basicpay;
    }
    public BigDecimal getAnnualincrement() {
        return this.annualincrement;
    }
    
    public void setAnnualincrement(BigDecimal annualincrement) {
        this.annualincrement = annualincrement;
    }
    public BigDecimal getFinalbasicpay() {
        return this.finalbasicpay;
    }
    
    public void setFinalbasicpay(BigDecimal finalbasicpay) {
        this.finalbasicpay = finalbasicpay;
    }
    public Date getPeriodfrom() {
        return this.periodfrom;
    }
    
    public void setPeriodfrom(Date periodfrom) {
        this.periodfrom = periodfrom;
    }
    public Date getPeriodto() {
        return this.periodto;
    }
    
    public void setPeriodto(Date periodto) {
        this.periodto = periodto;
    }
    public String getEmpearningscode() {
        return this.empearningscode;
    }
    
    public void setEmpearningscode(String empearningscode) {
        this.empearningscode = empearningscode;
    }
    public String getEmpdeductionscode() {
        return this.empdeductionscode;
    }
    
    public void setEmpdeductionscode(String empdeductionscode) {
        this.empdeductionscode = empdeductionscode;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }




}


