package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Professionaltaxslap generated by hbm2java
 */
public class Professionaltaxslap  implements java.io.Serializable {


     private String id;
     private String regioncode;
     private Date periodfrom;
     private Date periodto;
     private BigDecimal amount;
     private String orderno;
     private BigDecimal amountrangefrom;
     private BigDecimal amountrangeto;
     private BigDecimal percentage;
     private Boolean synchronized_;
     private Boolean cancelled;
     private String deductioncode;

    public Professionaltaxslap() {
    }

	
    public Professionaltaxslap(String id, String regioncode) {
        this.id = id;
        this.regioncode = regioncode;
    }
    public Professionaltaxslap(String id, String regioncode, Date periodfrom, Date periodto, BigDecimal amount, String orderno, BigDecimal amountrangefrom, BigDecimal amountrangeto, BigDecimal percentage, Boolean synchronized_, Boolean cancelled, String deductioncode) {
       this.id = id;
       this.regioncode = regioncode;
       this.periodfrom = periodfrom;
       this.periodto = periodto;
       this.amount = amount;
       this.orderno = orderno;
       this.amountrangefrom = amountrangefrom;
       this.amountrangeto = amountrangeto;
       this.percentage = percentage;
       this.synchronized_ = synchronized_;
       this.cancelled = cancelled;
       this.deductioncode = deductioncode;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRegioncode() {
        return this.regioncode;
    }
    
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }
    public Date getPeriodfrom() {
        return this.periodfrom;
    }
    
    public void setPeriodfrom(Date periodfrom) {
        this.periodfrom = periodfrom;
    }
    public Date getPeriodto() {
        return this.periodto;
    }
    
    public void setPeriodto(Date periodto) {
        this.periodto = periodto;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public BigDecimal getAmountrangefrom() {
        return this.amountrangefrom;
    }
    
    public void setAmountrangefrom(BigDecimal amountrangefrom) {
        this.amountrangefrom = amountrangefrom;
    }
    public BigDecimal getAmountrangeto() {
        return this.amountrangeto;
    }
    
    public void setAmountrangeto(BigDecimal amountrangeto) {
        this.amountrangeto = amountrangeto;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getDeductioncode() {
        return this.deductioncode;
    }
    
    public void setDeductioncode(String deductioncode) {
        this.deductioncode = deductioncode;
    }




}


