package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receiptpaymentdetails generated by hbm2java
 */
public class Receiptpaymentdetails  implements java.io.Serializable {


     private String id;
     private Bankchallan bankchallan;
     private Bankledger bankledger;
     private Partyledger partyledger;
     private Voucher voucher;
     private Chequedetails chequedetails;
     private Paymentmode paymentmode;
     private String refno;
     private String chequeno;
     private BigDecimal amount;
     private Boolean cancelled;
     private String region;
     private Integer serialno;
     private Date chequedate;
     private String favourof;
     private Date createddate;
     private String createdby;
     private String otherbankname;
     private Boolean realized;
     private Date realizeddate;
     private Set receiptpaymentdetailshistories = new HashSet(0);

    public Receiptpaymentdetails() {
    }

	
    public Receiptpaymentdetails(String id, Partyledger partyledger) {
        this.id = id;
        this.partyledger = partyledger;
    }
    public Receiptpaymentdetails(String id, Bankchallan bankchallan, Bankledger bankledger, Partyledger partyledger, Voucher voucher, Chequedetails chequedetails, Paymentmode paymentmode, String refno, String chequeno, BigDecimal amount, Boolean cancelled, String region, Integer serialno, Date chequedate, String favourof, Date createddate, String createdby, String otherbankname, Boolean realized, Date realizeddate, Set receiptpaymentdetailshistories) {
       this.id = id;
       this.bankchallan = bankchallan;
       this.bankledger = bankledger;
       this.partyledger = partyledger;
       this.voucher = voucher;
       this.chequedetails = chequedetails;
       this.paymentmode = paymentmode;
       this.refno = refno;
       this.chequeno = chequeno;
       this.amount = amount;
       this.cancelled = cancelled;
       this.region = region;
       this.serialno = serialno;
       this.chequedate = chequedate;
       this.favourof = favourof;
       this.createddate = createddate;
       this.createdby = createdby;
       this.otherbankname = otherbankname;
       this.realized = realized;
       this.realizeddate = realizeddate;
       this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Bankchallan getBankchallan() {
        return this.bankchallan;
    }
    
    public void setBankchallan(Bankchallan bankchallan) {
        this.bankchallan = bankchallan;
    }
    public Bankledger getBankledger() {
        return this.bankledger;
    }
    
    public void setBankledger(Bankledger bankledger) {
        this.bankledger = bankledger;
    }
    public Partyledger getPartyledger() {
        return this.partyledger;
    }
    
    public void setPartyledger(Partyledger partyledger) {
        this.partyledger = partyledger;
    }
    public Voucher getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(Voucher voucher) {
        this.voucher = voucher;
    }
    public Chequedetails getChequedetails() {
        return this.chequedetails;
    }
    
    public void setChequedetails(Chequedetails chequedetails) {
        this.chequedetails = chequedetails;
    }
    public Paymentmode getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(Paymentmode paymentmode) {
        this.paymentmode = paymentmode;
    }
    public String getRefno() {
        return this.refno;
    }
    
    public void setRefno(String refno) {
        this.refno = refno;
    }
    public String getChequeno() {
        return this.chequeno;
    }
    
    public void setChequeno(String chequeno) {
        this.chequeno = chequeno;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    public Date getChequedate() {
        return this.chequedate;
    }
    
    public void setChequedate(Date chequedate) {
        this.chequedate = chequedate;
    }
    public String getFavourof() {
        return this.favourof;
    }
    
    public void setFavourof(String favourof) {
        this.favourof = favourof;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getOtherbankname() {
        return this.otherbankname;
    }
    
    public void setOtherbankname(String otherbankname) {
        this.otherbankname = otherbankname;
    }
    public Boolean getRealized() {
        return this.realized;
    }
    
    public void setRealized(Boolean realized) {
        this.realized = realized;
    }
    public Date getRealizeddate() {
        return this.realizeddate;
    }
    
    public void setRealizeddate(Date realizeddate) {
        this.realizeddate = realizeddate;
    }
    public Set getReceiptpaymentdetailshistories() {
        return this.receiptpaymentdetailshistories;
    }
    
    public void setReceiptpaymentdetailshistories(Set receiptpaymentdetailshistories) {
        this.receiptpaymentdetailshistories = receiptpaymentdetailshistories;
    }




}


