package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Receiptpaymentdetailspending generated by hbm2java
 */
public class Receiptpaymentdetailspending  implements java.io.Serializable {


     private String id;
     private String partyledger;
     private String bankname;
     private String voucher;
     private String paymentmode;
     private String refno;
     private String chequedetails;
     private String chequeno;
     private BigDecimal amount;
     private Boolean cancelled;
     private String region;
     private Integer serialno;
     private Date chequedate;
     private String favourof;
     private Date createddate;
     private String createdby;
     private String otherbankname;
     private String bankchallan;
     private Boolean realized;
     private Date realizeddate;
     private String accountingperiod;
     private String accountbook;

    public Receiptpaymentdetailspending() {
    }

	
    public Receiptpaymentdetailspending(String id, String partyledger) {
        this.id = id;
        this.partyledger = partyledger;
    }
    public Receiptpaymentdetailspending(String id, String partyledger, String bankname, String voucher, String paymentmode, String refno, String chequedetails, String chequeno, BigDecimal amount, Boolean cancelled, String region, Integer serialno, Date chequedate, String favourof, Date createddate, String createdby, String otherbankname, String bankchallan, Boolean realized, Date realizeddate, String accountingperiod, String accountbook) {
       this.id = id;
       this.partyledger = partyledger;
       this.bankname = bankname;
       this.voucher = voucher;
       this.paymentmode = paymentmode;
       this.refno = refno;
       this.chequedetails = chequedetails;
       this.chequeno = chequeno;
       this.amount = amount;
       this.cancelled = cancelled;
       this.region = region;
       this.serialno = serialno;
       this.chequedate = chequedate;
       this.favourof = favourof;
       this.createddate = createddate;
       this.createdby = createdby;
       this.otherbankname = otherbankname;
       this.bankchallan = bankchallan;
       this.realized = realized;
       this.realizeddate = realizeddate;
       this.accountingperiod = accountingperiod;
       this.accountbook = accountbook;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPartyledger() {
        return this.partyledger;
    }
    
    public void setPartyledger(String partyledger) {
        this.partyledger = partyledger;
    }
    public String getBankname() {
        return this.bankname;
    }
    
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
    public String getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }
    public String getRefno() {
        return this.refno;
    }
    
    public void setRefno(String refno) {
        this.refno = refno;
    }
    public String getChequedetails() {
        return this.chequedetails;
    }
    
    public void setChequedetails(String chequedetails) {
        this.chequedetails = chequedetails;
    }
    public String getChequeno() {
        return this.chequeno;
    }
    
    public void setChequeno(String chequeno) {
        this.chequeno = chequeno;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    public Date getChequedate() {
        return this.chequedate;
    }
    
    public void setChequedate(Date chequedate) {
        this.chequedate = chequedate;
    }
    public String getFavourof() {
        return this.favourof;
    }
    
    public void setFavourof(String favourof) {
        this.favourof = favourof;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getOtherbankname() {
        return this.otherbankname;
    }
    
    public void setOtherbankname(String otherbankname) {
        this.otherbankname = otherbankname;
    }
    public String getBankchallan() {
        return this.bankchallan;
    }
    
    public void setBankchallan(String bankchallan) {
        this.bankchallan = bankchallan;
    }
    public Boolean getRealized() {
        return this.realized;
    }
    
    public void setRealized(Boolean realized) {
        this.realized = realized;
    }
    public Date getRealizeddate() {
        return this.realizeddate;
    }
    
    public void setRealizeddate(Date realizeddate) {
        this.realizeddate = realizeddate;
    }
    public String getAccountingperiod() {
        return this.accountingperiod;
    }
    
    public void setAccountingperiod(String accountingperiod) {
        this.accountingperiod = accountingperiod;
    }
    public String getAccountbook() {
        return this.accountbook;
    }
    
    public void setAccountbook(String accountbook) {
        this.accountbook = accountbook;
    }




}


