package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * ReferencecodesId generated by hbm2java
 */
public class ReferencecodesId  implements java.io.Serializable {


     private String parentcode;
     private String childcode;

    public ReferencecodesId() {
    }

    public ReferencecodesId(String parentcode, String childcode) {
       this.parentcode = parentcode;
       this.childcode = childcode;
    }
   
    public String getParentcode() {
        return this.parentcode;
    }
    
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }
    public String getChildcode() {
        return this.childcode;
    }
    
    public void setChildcode(String childcode) {
        this.childcode = childcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReferencecodesId) ) return false;
		 ReferencecodesId castOther = ( ReferencecodesId ) other; 
         
		 return ( (this.getParentcode()==castOther.getParentcode()) || ( this.getParentcode()!=null && castOther.getParentcode()!=null && this.getParentcode().equals(castOther.getParentcode()) ) )
 && ( (this.getChildcode()==castOther.getChildcode()) || ( this.getChildcode()!=null && castOther.getChildcode()!=null && this.getChildcode().equals(castOther.getChildcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getParentcode() == null ? 0 : this.getParentcode().hashCode() );
         result = 37 * result + ( getChildcode() == null ? 0 : this.getChildcode().hashCode() );
         return result;
   }   


}


