package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Referencecodes generated by hbm2java
 */
public class Referencecodes  implements java.io.Serializable {


     private ReferencecodesId id;
     private String description;
     private String childof;
     private String isuserdriven;

    public Referencecodes() {
    }

	
    public Referencecodes(ReferencecodesId id, String isuserdriven) {
        this.id = id;
        this.isuserdriven = isuserdriven;
    }
    public Referencecodes(ReferencecodesId id, String description, String childof, String isuserdriven) {
       this.id = id;
       this.description = description;
       this.childof = childof;
       this.isuserdriven = isuserdriven;
    }
   
    public ReferencecodesId getId() {
        return this.id;
    }
    
    public void setId(ReferencecodesId id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getChildof() {
        return this.childof;
    }
    
    public void setChildof(String childof) {
        this.childof = childof;
    }
    public String getIsuserdriven() {
        return this.isuserdriven;
    }
    
    public void setIsuserdriven(String isuserdriven) {
        this.isuserdriven = isuserdriven;
    }




}


