package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salarystructure generated by hbm2java
 */
public class Salarystructure  implements java.io.Serializable {


     private String id;
     private Employeemaster employeemaster;
     private Date periodfrom;
     private Date periodto;
     private BigDecimal amount;
     private BigDecimal percentage;
     private Boolean ispercentage;
     private String orderno;
     private Boolean synchronized_;
     private String accregion;
     private Date createddate;
     private String createdby;
     private Set employeedeductiondetailses = new HashSet(0);
     private Set employeeearningsdetailses = new HashSet(0);

    public Salarystructure() {
    }

	
    public Salarystructure(String id) {
        this.id = id;
    }
    public Salarystructure(String id, Employeemaster employeemaster, Date periodfrom, Date periodto, BigDecimal amount, BigDecimal percentage, Boolean ispercentage, String orderno, Boolean synchronized_, String accregion, Date createddate, String createdby, Set employeedeductiondetailses, Set employeeearningsdetailses) {
       this.id = id;
       this.employeemaster = employeemaster;
       this.periodfrom = periodfrom;
       this.periodto = periodto;
       this.amount = amount;
       this.percentage = percentage;
       this.ispercentage = ispercentage;
       this.orderno = orderno;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
       this.createddate = createddate;
       this.createdby = createdby;
       this.employeedeductiondetailses = employeedeductiondetailses;
       this.employeeearningsdetailses = employeeearningsdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Date getPeriodfrom() {
        return this.periodfrom;
    }
    
    public void setPeriodfrom(Date periodfrom) {
        this.periodfrom = periodfrom;
    }
    public Date getPeriodto() {
        return this.periodto;
    }
    
    public void setPeriodto(Date periodto) {
        this.periodto = periodto;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public Boolean getIspercentage() {
        return this.ispercentage;
    }
    
    public void setIspercentage(Boolean ispercentage) {
        this.ispercentage = ispercentage;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Set getEmployeedeductiondetailses() {
        return this.employeedeductiondetailses;
    }
    
    public void setEmployeedeductiondetailses(Set employeedeductiondetailses) {
        this.employeedeductiondetailses = employeedeductiondetailses;
    }
    public Set getEmployeeearningsdetailses() {
        return this.employeeearningsdetailses;
    }
    
    public void setEmployeeearningsdetailses(Set employeeearningsdetailses) {
        this.employeeearningsdetailses = employeeearningsdetailses;
    }




}


