package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Sectionmaster generated by hbm2java
 */
public class Sectionmaster  implements java.io.Serializable {


     private String id;
     private String sectionname;
     private Boolean synchronized_;
     private String parentcode;
     private String region;

    public Sectionmaster() {
    }

	
    public Sectionmaster(String id) {
        this.id = id;
    }
    public Sectionmaster(String id, String sectionname, Boolean synchronized_, String parentcode, String region) {
       this.id = id;
       this.sectionname = sectionname;
       this.synchronized_ = synchronized_;
       this.parentcode = parentcode;
       this.region = region;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSectionname() {
        return this.sectionname;
    }
    
    public void setSectionname(String sectionname) {
        this.sectionname = sectionname;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getParentcode() {
        return this.parentcode;
    }
    
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }




}


