package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supplementarysalarystructure generated by hbm2java
 */
public class Supplementarysalarystructure  implements java.io.Serializable {


     private String id;
     private Date periodfrom;
     private Date periodto;
     private BigDecimal amount;
     private BigDecimal percentage;
     private Boolean ispercentage;
     private String orderno;
     private Boolean synchronized_;
     private String accregion;
     private Boolean cancelled;
     private String supplementatypaybillid;
     private String supplementarypayrollprocessingdetailsid;
     private Date createddate;
     private String createdby;
     private Set supplementaryemployeedeductiondetailses = new HashSet(0);
     private Set supplementaryemployeeearningsdetailses = new HashSet(0);

    public Supplementarysalarystructure() {
    }

	
    public Supplementarysalarystructure(String id) {
        this.id = id;
    }
    public Supplementarysalarystructure(String id, Date periodfrom, Date periodto, BigDecimal amount, BigDecimal percentage, Boolean ispercentage, String orderno, Boolean synchronized_, String accregion, Boolean cancelled, String supplementatypaybillid, String supplementarypayrollprocessingdetailsid, Date createddate, String createdby, Set supplementaryemployeedeductiondetailses, Set supplementaryemployeeearningsdetailses) {
       this.id = id;
       this.periodfrom = periodfrom;
       this.periodto = periodto;
       this.amount = amount;
       this.percentage = percentage;
       this.ispercentage = ispercentage;
       this.orderno = orderno;
       this.synchronized_ = synchronized_;
       this.accregion = accregion;
       this.cancelled = cancelled;
       this.supplementatypaybillid = supplementatypaybillid;
       this.supplementarypayrollprocessingdetailsid = supplementarypayrollprocessingdetailsid;
       this.createddate = createddate;
       this.createdby = createdby;
       this.supplementaryemployeedeductiondetailses = supplementaryemployeedeductiondetailses;
       this.supplementaryemployeeearningsdetailses = supplementaryemployeeearningsdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Date getPeriodfrom() {
        return this.periodfrom;
    }
    
    public void setPeriodfrom(Date periodfrom) {
        this.periodfrom = periodfrom;
    }
    public Date getPeriodto() {
        return this.periodto;
    }
    
    public void setPeriodto(Date periodto) {
        this.periodto = periodto;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public Boolean getIspercentage() {
        return this.ispercentage;
    }
    
    public void setIspercentage(Boolean ispercentage) {
        this.ispercentage = ispercentage;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public Boolean getSynchronized_() {
        return this.synchronized_;
    }
    
    public void setSynchronized_(Boolean synchronized_) {
        this.synchronized_ = synchronized_;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getSupplementatypaybillid() {
        return this.supplementatypaybillid;
    }
    
    public void setSupplementatypaybillid(String supplementatypaybillid) {
        this.supplementatypaybillid = supplementatypaybillid;
    }
    public String getSupplementarypayrollprocessingdetailsid() {
        return this.supplementarypayrollprocessingdetailsid;
    }
    
    public void setSupplementarypayrollprocessingdetailsid(String supplementarypayrollprocessingdetailsid) {
        this.supplementarypayrollprocessingdetailsid = supplementarypayrollprocessingdetailsid;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Set getSupplementaryemployeedeductiondetailses() {
        return this.supplementaryemployeedeductiondetailses;
    }
    
    public void setSupplementaryemployeedeductiondetailses(Set supplementaryemployeedeductiondetailses) {
        this.supplementaryemployeedeductiondetailses = supplementaryemployeedeductiondetailses;
    }
    public Set getSupplementaryemployeeearningsdetailses() {
        return this.supplementaryemployeeearningsdetailses;
    }
    
    public void setSupplementaryemployeeearningsdetailses(Set supplementaryemployeeearningsdetailses) {
        this.supplementaryemployeeearningsdetailses = supplementaryemployeeearningsdetailses;
    }




}


