package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supplementatypaybill generated by hbm2java
 */
public class Supplementatypaybill  implements java.io.Serializable {


     private String id;
     private Employeemaster employeemaster;
     private Dabatchdetails dabatchdetails;
     private String accregion;
     private BigDecimal noofdays;
     private Date date;
     private String type;
     private Boolean cancelled;
     private String section;
     private String subsection;
     private String paymentmode;
     private Date sldate;
     private String employeecategory;
     private String designation;
     private Date createddate;
     private String createdby;
     private Set supplementarypayrollprocessingdetailses = new HashSet(0);

    public Supplementatypaybill() {
    }

	
    public Supplementatypaybill(String id) {
        this.id = id;
    }
    public Supplementatypaybill(String id, Employeemaster employeemaster, Dabatchdetails dabatchdetails, String accregion, BigDecimal noofdays, Date date, String type, Boolean cancelled, String section, String subsection, String paymentmode, Date sldate, String employeecategory, String designation, Date createddate, String createdby, Set supplementarypayrollprocessingdetailses) {
       this.id = id;
       this.employeemaster = employeemaster;
       this.dabatchdetails = dabatchdetails;
       this.accregion = accregion;
       this.noofdays = noofdays;
       this.date = date;
       this.type = type;
       this.cancelled = cancelled;
       this.section = section;
       this.subsection = subsection;
       this.paymentmode = paymentmode;
       this.sldate = sldate;
       this.employeecategory = employeecategory;
       this.designation = designation;
       this.createddate = createddate;
       this.createdby = createdby;
       this.supplementarypayrollprocessingdetailses = supplementarypayrollprocessingdetailses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Dabatchdetails getDabatchdetails() {
        return this.dabatchdetails;
    }
    
    public void setDabatchdetails(Dabatchdetails dabatchdetails) {
        this.dabatchdetails = dabatchdetails;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public BigDecimal getNoofdays() {
        return this.noofdays;
    }
    
    public void setNoofdays(BigDecimal noofdays) {
        this.noofdays = noofdays;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getSubsection() {
        return this.subsection;
    }
    
    public void setSubsection(String subsection) {
        this.subsection = subsection;
    }
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }
    public Date getSldate() {
        return this.sldate;
    }
    
    public void setSldate(Date sldate) {
        this.sldate = sldate;
    }
    public String getEmployeecategory() {
        return this.employeecategory;
    }
    
    public void setEmployeecategory(String employeecategory) {
        this.employeecategory = employeecategory;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Set getSupplementarypayrollprocessingdetailses() {
        return this.supplementarypayrollprocessingdetailses;
    }
    
    public void setSupplementarypayrollprocessingdetailses(Set supplementarypayrollprocessingdetailses) {
        this.supplementarypayrollprocessingdetailses = supplementarypayrollprocessingdetailses;
    }




}


