package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Supplementaryemployeeloansandadvancesdetails generated by hbm2java
 */
public class Supplementaryemployeeloansandadvancesdetails  implements java.io.Serializable {


     private String id;
     private Supplementarypayrollprocessingdetails supplementarypayrollprocessingdetails;
     private Employeeloansandadvances employeeloansandadvances;
     private Integer nthinstallment;
     private BigDecimal installmentamount;
     private BigDecimal loanbalance;
     private Boolean cancelled;
     private String accregion;
     private Date createddate;
     private String createdby;

    public Supplementaryemployeeloansandadvancesdetails() {
    }

	
    public Supplementaryemployeeloansandadvancesdetails(String id) {
        this.id = id;
    }
    public Supplementaryemployeeloansandadvancesdetails(String id, Supplementarypayrollprocessingdetails supplementarypayrollprocessingdetails, Employeeloansandadvances employeeloansandadvances, Integer nthinstallment, BigDecimal installmentamount, BigDecimal loanbalance, Boolean cancelled, String accregion, Date createddate, String createdby) {
       this.id = id;
       this.supplementarypayrollprocessingdetails = supplementarypayrollprocessingdetails;
       this.employeeloansandadvances = employeeloansandadvances;
       this.nthinstallment = nthinstallment;
       this.installmentamount = installmentamount;
       this.loanbalance = loanbalance;
       this.cancelled = cancelled;
       this.accregion = accregion;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Supplementarypayrollprocessingdetails getSupplementarypayrollprocessingdetails() {
        return this.supplementarypayrollprocessingdetails;
    }
    
    public void setSupplementarypayrollprocessingdetails(Supplementarypayrollprocessingdetails supplementarypayrollprocessingdetails) {
        this.supplementarypayrollprocessingdetails = supplementarypayrollprocessingdetails;
    }
    public Employeeloansandadvances getEmployeeloansandadvances() {
        return this.employeeloansandadvances;
    }
    
    public void setEmployeeloansandadvances(Employeeloansandadvances employeeloansandadvances) {
        this.employeeloansandadvances = employeeloansandadvances;
    }
    public Integer getNthinstallment() {
        return this.nthinstallment;
    }
    
    public void setNthinstallment(Integer nthinstallment) {
        this.nthinstallment = nthinstallment;
    }
    public BigDecimal getInstallmentamount() {
        return this.installmentamount;
    }
    
    public void setInstallmentamount(BigDecimal installmentamount) {
        this.installmentamount = installmentamount;
    }
    public BigDecimal getLoanbalance() {
        return this.loanbalance;
    }
    
    public void setLoanbalance(BigDecimal loanbalance) {
        this.loanbalance = loanbalance;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


