package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Supplementaryemployeedeductiondetails generated by hbm2java
 */
public class Supplementaryemployeedeductiondetails  implements java.io.Serializable {


     private String id;
     private Supplementarysalarystructure supplementarysalarystructure;
     private String deductionmasterid;
     private BigDecimal amount;
     private String dednNo;
     private Boolean cancelled;
     private String accregion;

    public Supplementaryemployeedeductiondetails() {
    }

	
    public Supplementaryemployeedeductiondetails(String id) {
        this.id = id;
    }
    public Supplementaryemployeedeductiondetails(String id, Supplementarysalarystructure supplementarysalarystructure, String deductionmasterid, BigDecimal amount, String dednNo, Boolean cancelled, String accregion) {
       this.id = id;
       this.supplementarysalarystructure = supplementarysalarystructure;
       this.deductionmasterid = deductionmasterid;
       this.amount = amount;
       this.dednNo = dednNo;
       this.cancelled = cancelled;
       this.accregion = accregion;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Supplementarysalarystructure getSupplementarysalarystructure() {
        return this.supplementarysalarystructure;
    }
    
    public void setSupplementarysalarystructure(Supplementarysalarystructure supplementarysalarystructure) {
        this.supplementarysalarystructure = supplementarysalarystructure;
    }
    public String getDeductionmasterid() {
        return this.deductionmasterid;
    }
    
    public void setDeductionmasterid(String deductionmasterid) {
        this.deductionmasterid = deductionmasterid;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getDednNo() {
        return this.dednNo;
    }
    
    public void setDednNo(String dednNo) {
        this.dednNo = dednNo;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }




}


