package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usertype generated by hbm2java
 */
public class Usertype  implements java.io.Serializable {


     private int id;
     private String usertypename;
     private Integer parentcode;
     private Set menuprivilageses = new HashSet(0);

    public Usertype() {
    }

	
    public Usertype(int id) {
        this.id = id;
    }
    public Usertype(int id, String usertypename, Integer parentcode, Set menuprivilageses) {
       this.id = id;
       this.usertypename = usertypename;
       this.parentcode = parentcode;
       this.menuprivilageses = menuprivilageses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsertypename() {
        return this.usertypename;
    }
    
    public void setUsertypename(String usertypename) {
        this.usertypename = usertypename;
    }
    public Integer getParentcode() {
        return this.parentcode;
    }
    
    public void setParentcode(Integer parentcode) {
        this.parentcode = parentcode;
    }
    public Set getMenuprivilageses() {
        return this.menuprivilageses;
    }
    
    public void setMenuprivilageses(Set menuprivilageses) {
        this.menuprivilageses = menuprivilageses;
    }




}


