package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Useroperatingrights generated by hbm2java
 */
public class Useroperatingrights  implements java.io.Serializable {


     private int id;
     private Usermaster usermaster;
     private int usertypeid;
     private Boolean accessright;

    public Useroperatingrights() {
    }

	
    public Useroperatingrights(int id, Usermaster usermaster, int usertypeid) {
        this.id = id;
        this.usermaster = usermaster;
        this.usertypeid = usertypeid;
    }
    public Useroperatingrights(int id, Usermaster usermaster, int usertypeid, Boolean accessright) {
       this.id = id;
       this.usermaster = usermaster;
       this.usertypeid = usertypeid;
       this.accessright = accessright;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usermaster getUsermaster() {
        return this.usermaster;
    }
    
    public void setUsermaster(Usermaster usermaster) {
        this.usermaster = usermaster;
    }
    public int getUsertypeid() {
        return this.usertypeid;
    }
    
    public void setUsertypeid(int usertypeid) {
        this.usertypeid = usertypeid;
    }
    public Boolean getAccessright() {
        return this.accessright;
    }
    
    public void setAccessright(Boolean accessright) {
        this.accessright = accessright;
    }




}


