package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Vatonpurchase generated by hbm2java
 */
public class Vatonpurchase  implements java.io.Serializable {


     private String id;
     private Commoditymaster commoditymaster;
     private Partyledger partyledger;
     private Regionmaster regionmaster;
     private Integer year;
     private Integer month;
     private BigDecimal quantity;
     private BigDecimal amount;
     private BigDecimal taxpercentage;
     private BigDecimal taxamount;
     private BigDecimal totamount;
     private String accregion;
     private String billno;
     private Date billdate;
     private Boolean cancelled;
     private String createdby;
     private Date createddate;
     private BigDecimal rate;

    public Vatonpurchase() {
    }

	
    public Vatonpurchase(String id) {
        this.id = id;
    }
    public Vatonpurchase(String id, Commoditymaster commoditymaster, Partyledger partyledger, Regionmaster regionmaster, Integer year, Integer month, BigDecimal quantity, BigDecimal amount, BigDecimal taxpercentage, BigDecimal taxamount, BigDecimal totamount, String accregion, String billno, Date billdate, Boolean cancelled, String createdby, Date createddate, BigDecimal rate) {
       this.id = id;
       this.commoditymaster = commoditymaster;
       this.partyledger = partyledger;
       this.regionmaster = regionmaster;
       this.year = year;
       this.month = month;
       this.quantity = quantity;
       this.amount = amount;
       this.taxpercentage = taxpercentage;
       this.taxamount = taxamount;
       this.totamount = totamount;
       this.accregion = accregion;
       this.billno = billno;
       this.billdate = billdate;
       this.cancelled = cancelled;
       this.createdby = createdby;
       this.createddate = createddate;
       this.rate = rate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Commoditymaster getCommoditymaster() {
        return this.commoditymaster;
    }
    
    public void setCommoditymaster(Commoditymaster commoditymaster) {
        this.commoditymaster = commoditymaster;
    }
    public Partyledger getPartyledger() {
        return this.partyledger;
    }
    
    public void setPartyledger(Partyledger partyledger) {
        this.partyledger = partyledger;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getTaxpercentage() {
        return this.taxpercentage;
    }
    
    public void setTaxpercentage(BigDecimal taxpercentage) {
        this.taxpercentage = taxpercentage;
    }
    public BigDecimal getTaxamount() {
        return this.taxamount;
    }
    
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }
    public BigDecimal getTotamount() {
        return this.totamount;
    }
    
    public void setTotamount(BigDecimal totamount) {
        this.totamount = totamount;
    }
    public String getAccregion() {
        return this.accregion;
    }
    
    public void setAccregion(String accregion) {
        this.accregion = accregion;
    }
    public String getBillno() {
        return this.billno;
    }
    
    public void setBillno(String billno) {
        this.billno = billno;
    }
    public Date getBilldate() {
        return this.billdate;
    }
    
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }




}


