package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Vouacq generated by hbm2java
 */
public class Vouacq  implements java.io.Serializable {


     private VouacqId id;
     private String ename;
     private String desg;
     private BigDecimal orderno;
     private BigDecimal amount;
     private Date startdate;

    public Vouacq() {
    }

	
    public Vouacq(VouacqId id) {
        this.id = id;
    }
    public Vouacq(VouacqId id, String ename, String desg, BigDecimal orderno, BigDecimal amount, Date startdate) {
       this.id = id;
       this.ename = ename;
       this.desg = desg;
       this.orderno = orderno;
       this.amount = amount;
       this.startdate = startdate;
    }
   
    public VouacqId getId() {
        return this.id;
    }
    
    public void setId(VouacqId id) {
        this.id = id;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getDesg() {
        return this.desg;
    }
    
    public void setDesg(String desg) {
        this.desg = desg;
    }
    public BigDecimal getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(BigDecimal orderno) {
        this.orderno = orderno;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }




}


