package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA



/**
 * VouacqId generated by hbm2java
 */
public class VouacqId  implements java.io.Serializable {


     private String ecpfno;
     private String vrno;

    public VouacqId() {
    }

    public VouacqId(String ecpfno, String vrno) {
       this.ecpfno = ecpfno;
       this.vrno = vrno;
    }
   
    public String getEcpfno() {
        return this.ecpfno;
    }
    
    public void setEcpfno(String ecpfno) {
        this.ecpfno = ecpfno;
    }
    public String getVrno() {
        return this.vrno;
    }
    
    public void setVrno(String vrno) {
        this.vrno = vrno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VouacqId) ) return false;
		 VouacqId castOther = ( VouacqId ) other; 
         
		 return ( (this.getEcpfno()==castOther.getEcpfno()) || ( this.getEcpfno()!=null && castOther.getEcpfno()!=null && this.getEcpfno().equals(castOther.getEcpfno()) ) )
 && ( (this.getVrno()==castOther.getVrno()) || ( this.getVrno()!=null && castOther.getVrno()!=null && this.getVrno().equals(castOther.getVrno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEcpfno() == null ? 0 : this.getEcpfno().hashCode() );
         result = 37 * result + ( getVrno() == null ? 0 : this.getVrno().hashCode() );
         return result;
   }   


}


