package com.onward.persistence.payroll;
// Generated 24 Aug, 2015 3:09:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Voucherdetailshistory generated by hbm2java
 */
public class Voucherdetailshistory  implements java.io.Serializable {


     private String id;
     private Voucherdetails voucherdetails;
     private Regionmaster regionmaster;
     private Voucher voucher;
     private Accountsheads accountsheads;
     private BigDecimal amount;
     private String voucheroption;
     private BigDecimal debit;
     private BigDecimal credit;
     private Boolean cancelled;
     private Integer serialno;
     private Date createddate;
     private String createdby;

    public Voucherdetailshistory() {
    }

	
    public Voucherdetailshistory(String id, Regionmaster regionmaster, Voucher voucher, Accountsheads accountsheads) {
        this.id = id;
        this.regionmaster = regionmaster;
        this.voucher = voucher;
        this.accountsheads = accountsheads;
    }
    public Voucherdetailshistory(String id, Voucherdetails voucherdetails, Regionmaster regionmaster, Voucher voucher, Accountsheads accountsheads, BigDecimal amount, String voucheroption, BigDecimal debit, BigDecimal credit, Boolean cancelled, Integer serialno, Date createddate, String createdby) {
       this.id = id;
       this.voucherdetails = voucherdetails;
       this.regionmaster = regionmaster;
       this.voucher = voucher;
       this.accountsheads = accountsheads;
       this.amount = amount;
       this.voucheroption = voucheroption;
       this.debit = debit;
       this.credit = credit;
       this.cancelled = cancelled;
       this.serialno = serialno;
       this.createddate = createddate;
       this.createdby = createdby;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Voucherdetails getVoucherdetails() {
        return this.voucherdetails;
    }
    
    public void setVoucherdetails(Voucherdetails voucherdetails) {
        this.voucherdetails = voucherdetails;
    }
    public Regionmaster getRegionmaster() {
        return this.regionmaster;
    }
    
    public void setRegionmaster(Regionmaster regionmaster) {
        this.regionmaster = regionmaster;
    }
    public Voucher getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(Voucher voucher) {
        this.voucher = voucher;
    }
    public Accountsheads getAccountsheads() {
        return this.accountsheads;
    }
    
    public void setAccountsheads(Accountsheads accountsheads) {
        this.accountsheads = accountsheads;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getVoucheroption() {
        return this.voucheroption;
    }
    
    public void setVoucheroption(String voucheroption) {
        this.voucheroption = voucheroption;
    }
    public BigDecimal getDebit() {
        return this.debit;
    }
    
    public void setDebit(BigDecimal debit) {
        this.debit = debit;
    }
    public BigDecimal getCredit() {
        return this.credit;
    }
    
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


